
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  active_sessions: 'active_sessions',
  auth_audit_logs: 'auth_audit_logs',
  otp_codes: 'otp_codes',
  persons: 'persons',
  refresh_tokens: 'refresh_tokens',
  users: 'users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Active_sessionsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  access_token_jti: 'access_token_jti',
  refresh_token_id: 'refresh_token_id',
  device_name: 'device_name',
  last_activity_at: 'last_activity_at',
  expires_at: 'expires_at',
  created_at: 'created_at'
} as const

export type Active_sessionsScalarFieldEnum = (typeof Active_sessionsScalarFieldEnum)[keyof typeof Active_sessionsScalarFieldEnum]


export const Auth_audit_logsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  event: 'event',
  details: 'details',
  created_at: 'created_at'
} as const

export type Auth_audit_logsScalarFieldEnum = (typeof Auth_audit_logsScalarFieldEnum)[keyof typeof Auth_audit_logsScalarFieldEnum]


export const Otp_codesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  code: 'code',
  expires_at: 'expires_at',
  is_used: 'is_used',
  attempts: 'attempts',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Otp_codesScalarFieldEnum = (typeof Otp_codesScalarFieldEnum)[keyof typeof Otp_codesScalarFieldEnum]


export const PersonsScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  paternal_last_name: 'paternal_last_name',
  maternal_last_name: 'maternal_last_name',
  birth_date: 'birth_date',
  gender: 'gender',
  address: 'address',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type PersonsScalarFieldEnum = (typeof PersonsScalarFieldEnum)[keyof typeof PersonsScalarFieldEnum]


export const Refresh_tokensScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  token_hash: 'token_hash',
  expires_at: 'expires_at',
  revoked_at: 'revoked_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Refresh_tokensScalarFieldEnum = (typeof Refresh_tokensScalarFieldEnum)[keyof typeof Refresh_tokensScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  person_id: 'person_id',
  email: 'email',
  phone: 'phone',
  password_hash: 'password_hash',
  two_factor_method: 'two_factor_method',
  is_active: 'is_active',
  failed_attempts: 'failed_attempts',
  blocked_until: 'blocked_until',
  last_login_at: 'last_login_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

