
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const audit_event_type = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  OTP_REQUESTED: 'OTP_REQUESTED',
  OTP_VALIDATED: 'OTP_VALIDATED',
  OTP_FAILED: 'OTP_FAILED',
  LOGOUT: 'LOGOUT',
  BLOCKED: 'BLOCKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED'
} as const

export type audit_event_type = (typeof audit_event_type)[keyof typeof audit_event_type]


export const gender_type = {
  M: 'M',
  F: 'F'
} as const

export type gender_type = (typeof gender_type)[keyof typeof gender_type]
