
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `active_sessions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model active_sessions
 * 
 */
export type active_sessionsModel = runtime.Types.Result.DefaultSelection<Prisma.$active_sessionsPayload>

export type AggregateActive_sessions = {
  _count: Active_sessionsCountAggregateOutputType | null
  _min: Active_sessionsMinAggregateOutputType | null
  _max: Active_sessionsMaxAggregateOutputType | null
}

export type Active_sessionsMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  access_token_jti: string | null
  refresh_token_id: string | null
  device_name: string | null
  last_activity_at: Date | null
  expires_at: Date | null
  created_at: Date | null
}

export type Active_sessionsMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  access_token_jti: string | null
  refresh_token_id: string | null
  device_name: string | null
  last_activity_at: Date | null
  expires_at: Date | null
  created_at: Date | null
}

export type Active_sessionsCountAggregateOutputType = {
  id: number
  user_id: number
  access_token_jti: number
  refresh_token_id: number
  device_name: number
  last_activity_at: number
  expires_at: number
  created_at: number
  _all: number
}


export type Active_sessionsMinAggregateInputType = {
  id?: true
  user_id?: true
  access_token_jti?: true
  refresh_token_id?: true
  device_name?: true
  last_activity_at?: true
  expires_at?: true
  created_at?: true
}

export type Active_sessionsMaxAggregateInputType = {
  id?: true
  user_id?: true
  access_token_jti?: true
  refresh_token_id?: true
  device_name?: true
  last_activity_at?: true
  expires_at?: true
  created_at?: true
}

export type Active_sessionsCountAggregateInputType = {
  id?: true
  user_id?: true
  access_token_jti?: true
  refresh_token_id?: true
  device_name?: true
  last_activity_at?: true
  expires_at?: true
  created_at?: true
  _all?: true
}

export type Active_sessionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which active_sessions to aggregate.
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of active_sessions to fetch.
   */
  orderBy?: Prisma.active_sessionsOrderByWithRelationInput | Prisma.active_sessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.active_sessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` active_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` active_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned active_sessions
  **/
  _count?: true | Active_sessionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Active_sessionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Active_sessionsMaxAggregateInputType
}

export type GetActive_sessionsAggregateType<T extends Active_sessionsAggregateArgs> = {
      [P in keyof T & keyof AggregateActive_sessions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActive_sessions[P]>
    : Prisma.GetScalarType<T[P], AggregateActive_sessions[P]>
}




export type active_sessionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.active_sessionsWhereInput
  orderBy?: Prisma.active_sessionsOrderByWithAggregationInput | Prisma.active_sessionsOrderByWithAggregationInput[]
  by: Prisma.Active_sessionsScalarFieldEnum[] | Prisma.Active_sessionsScalarFieldEnum
  having?: Prisma.active_sessionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Active_sessionsCountAggregateInputType | true
  _min?: Active_sessionsMinAggregateInputType
  _max?: Active_sessionsMaxAggregateInputType
}

export type Active_sessionsGroupByOutputType = {
  id: string
  user_id: string
  access_token_jti: string
  refresh_token_id: string
  device_name: string | null
  last_activity_at: Date
  expires_at: Date
  created_at: Date | null
  _count: Active_sessionsCountAggregateOutputType | null
  _min: Active_sessionsMinAggregateOutputType | null
  _max: Active_sessionsMaxAggregateOutputType | null
}

export type GetActive_sessionsGroupByPayload<T extends active_sessionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Active_sessionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Active_sessionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Active_sessionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Active_sessionsGroupByOutputType[P]>
      }
    >
  >



export type active_sessionsWhereInput = {
  AND?: Prisma.active_sessionsWhereInput | Prisma.active_sessionsWhereInput[]
  OR?: Prisma.active_sessionsWhereInput[]
  NOT?: Prisma.active_sessionsWhereInput | Prisma.active_sessionsWhereInput[]
  id?: Prisma.UuidFilter<"active_sessions"> | string
  user_id?: Prisma.UuidFilter<"active_sessions"> | string
  access_token_jti?: Prisma.StringFilter<"active_sessions"> | string
  refresh_token_id?: Prisma.UuidFilter<"active_sessions"> | string
  device_name?: Prisma.StringNullableFilter<"active_sessions"> | string | null
  last_activity_at?: Prisma.DateTimeFilter<"active_sessions"> | Date | string
  expires_at?: Prisma.DateTimeFilter<"active_sessions"> | Date | string
  created_at?: Prisma.DateTimeNullableFilter<"active_sessions"> | Date | string | null
  refresh_tokens?: Prisma.XOR<Prisma.Refresh_tokensScalarRelationFilter, Prisma.refresh_tokensWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type active_sessionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token_jti?: Prisma.SortOrder
  refresh_token_id?: Prisma.SortOrder
  device_name?: Prisma.SortOrderInput | Prisma.SortOrder
  last_activity_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_tokens?: Prisma.refresh_tokensOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type active_sessionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.active_sessionsWhereInput | Prisma.active_sessionsWhereInput[]
  OR?: Prisma.active_sessionsWhereInput[]
  NOT?: Prisma.active_sessionsWhereInput | Prisma.active_sessionsWhereInput[]
  user_id?: Prisma.UuidFilter<"active_sessions"> | string
  access_token_jti?: Prisma.StringFilter<"active_sessions"> | string
  refresh_token_id?: Prisma.UuidFilter<"active_sessions"> | string
  device_name?: Prisma.StringNullableFilter<"active_sessions"> | string | null
  last_activity_at?: Prisma.DateTimeFilter<"active_sessions"> | Date | string
  expires_at?: Prisma.DateTimeFilter<"active_sessions"> | Date | string
  created_at?: Prisma.DateTimeNullableFilter<"active_sessions"> | Date | string | null
  refresh_tokens?: Prisma.XOR<Prisma.Refresh_tokensScalarRelationFilter, Prisma.refresh_tokensWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "id">

export type active_sessionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token_jti?: Prisma.SortOrder
  refresh_token_id?: Prisma.SortOrder
  device_name?: Prisma.SortOrderInput | Prisma.SortOrder
  last_activity_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.active_sessionsCountOrderByAggregateInput
  _max?: Prisma.active_sessionsMaxOrderByAggregateInput
  _min?: Prisma.active_sessionsMinOrderByAggregateInput
}

export type active_sessionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.active_sessionsScalarWhereWithAggregatesInput | Prisma.active_sessionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.active_sessionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.active_sessionsScalarWhereWithAggregatesInput | Prisma.active_sessionsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"active_sessions"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"active_sessions"> | string
  access_token_jti?: Prisma.StringWithAggregatesFilter<"active_sessions"> | string
  refresh_token_id?: Prisma.UuidWithAggregatesFilter<"active_sessions"> | string
  device_name?: Prisma.StringNullableWithAggregatesFilter<"active_sessions"> | string | null
  last_activity_at?: Prisma.DateTimeWithAggregatesFilter<"active_sessions"> | Date | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"active_sessions"> | Date | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"active_sessions"> | Date | string | null
}

export type active_sessionsCreateInput = {
  id?: string
  access_token_jti: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
  refresh_tokens: Prisma.refresh_tokensCreateNestedOneWithoutActive_sessionsInput
  users: Prisma.usersCreateNestedOneWithoutActive_sessionsInput
}

export type active_sessionsUncheckedCreateInput = {
  id?: string
  user_id: string
  access_token_jti: string
  refresh_token_id: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
}

export type active_sessionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_tokens?: Prisma.refresh_tokensUpdateOneRequiredWithoutActive_sessionsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutActive_sessionsNestedInput
}

export type active_sessionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  refresh_token_id?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type active_sessionsCreateManyInput = {
  id?: string
  user_id: string
  access_token_jti: string
  refresh_token_id: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
}

export type active_sessionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type active_sessionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  refresh_token_id?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type active_sessionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token_jti?: Prisma.SortOrder
  refresh_token_id?: Prisma.SortOrder
  device_name?: Prisma.SortOrder
  last_activity_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type active_sessionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token_jti?: Prisma.SortOrder
  refresh_token_id?: Prisma.SortOrder
  device_name?: Prisma.SortOrder
  last_activity_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type active_sessionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token_jti?: Prisma.SortOrder
  refresh_token_id?: Prisma.SortOrder
  device_name?: Prisma.SortOrder
  last_activity_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type Active_sessionsListRelationFilter = {
  every?: Prisma.active_sessionsWhereInput
  some?: Prisma.active_sessionsWhereInput
  none?: Prisma.active_sessionsWhereInput
}

export type active_sessionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type active_sessionsCreateNestedManyWithoutRefresh_tokensInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput> | Prisma.active_sessionsCreateWithoutRefresh_tokensInput[] | Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput | Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput[]
  createMany?: Prisma.active_sessionsCreateManyRefresh_tokensInputEnvelope
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
}

export type active_sessionsUncheckedCreateNestedManyWithoutRefresh_tokensInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput> | Prisma.active_sessionsCreateWithoutRefresh_tokensInput[] | Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput | Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput[]
  createMany?: Prisma.active_sessionsCreateManyRefresh_tokensInputEnvelope
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
}

export type active_sessionsUpdateManyWithoutRefresh_tokensNestedInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput> | Prisma.active_sessionsCreateWithoutRefresh_tokensInput[] | Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput | Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput[]
  upsert?: Prisma.active_sessionsUpsertWithWhereUniqueWithoutRefresh_tokensInput | Prisma.active_sessionsUpsertWithWhereUniqueWithoutRefresh_tokensInput[]
  createMany?: Prisma.active_sessionsCreateManyRefresh_tokensInputEnvelope
  set?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  disconnect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  delete?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  update?: Prisma.active_sessionsUpdateWithWhereUniqueWithoutRefresh_tokensInput | Prisma.active_sessionsUpdateWithWhereUniqueWithoutRefresh_tokensInput[]
  updateMany?: Prisma.active_sessionsUpdateManyWithWhereWithoutRefresh_tokensInput | Prisma.active_sessionsUpdateManyWithWhereWithoutRefresh_tokensInput[]
  deleteMany?: Prisma.active_sessionsScalarWhereInput | Prisma.active_sessionsScalarWhereInput[]
}

export type active_sessionsUncheckedUpdateManyWithoutRefresh_tokensNestedInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput> | Prisma.active_sessionsCreateWithoutRefresh_tokensInput[] | Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput | Prisma.active_sessionsCreateOrConnectWithoutRefresh_tokensInput[]
  upsert?: Prisma.active_sessionsUpsertWithWhereUniqueWithoutRefresh_tokensInput | Prisma.active_sessionsUpsertWithWhereUniqueWithoutRefresh_tokensInput[]
  createMany?: Prisma.active_sessionsCreateManyRefresh_tokensInputEnvelope
  set?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  disconnect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  delete?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  update?: Prisma.active_sessionsUpdateWithWhereUniqueWithoutRefresh_tokensInput | Prisma.active_sessionsUpdateWithWhereUniqueWithoutRefresh_tokensInput[]
  updateMany?: Prisma.active_sessionsUpdateManyWithWhereWithoutRefresh_tokensInput | Prisma.active_sessionsUpdateManyWithWhereWithoutRefresh_tokensInput[]
  deleteMany?: Prisma.active_sessionsScalarWhereInput | Prisma.active_sessionsScalarWhereInput[]
}

export type active_sessionsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutUsersInput, Prisma.active_sessionsUncheckedCreateWithoutUsersInput> | Prisma.active_sessionsCreateWithoutUsersInput[] | Prisma.active_sessionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutUsersInput | Prisma.active_sessionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.active_sessionsCreateManyUsersInputEnvelope
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
}

export type active_sessionsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutUsersInput, Prisma.active_sessionsUncheckedCreateWithoutUsersInput> | Prisma.active_sessionsCreateWithoutUsersInput[] | Prisma.active_sessionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutUsersInput | Prisma.active_sessionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.active_sessionsCreateManyUsersInputEnvelope
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
}

export type active_sessionsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutUsersInput, Prisma.active_sessionsUncheckedCreateWithoutUsersInput> | Prisma.active_sessionsCreateWithoutUsersInput[] | Prisma.active_sessionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutUsersInput | Prisma.active_sessionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.active_sessionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.active_sessionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.active_sessionsCreateManyUsersInputEnvelope
  set?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  disconnect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  delete?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  update?: Prisma.active_sessionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.active_sessionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.active_sessionsUpdateManyWithWhereWithoutUsersInput | Prisma.active_sessionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.active_sessionsScalarWhereInput | Prisma.active_sessionsScalarWhereInput[]
}

export type active_sessionsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.active_sessionsCreateWithoutUsersInput, Prisma.active_sessionsUncheckedCreateWithoutUsersInput> | Prisma.active_sessionsCreateWithoutUsersInput[] | Prisma.active_sessionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.active_sessionsCreateOrConnectWithoutUsersInput | Prisma.active_sessionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.active_sessionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.active_sessionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.active_sessionsCreateManyUsersInputEnvelope
  set?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  disconnect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  delete?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  connect?: Prisma.active_sessionsWhereUniqueInput | Prisma.active_sessionsWhereUniqueInput[]
  update?: Prisma.active_sessionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.active_sessionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.active_sessionsUpdateManyWithWhereWithoutUsersInput | Prisma.active_sessionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.active_sessionsScalarWhereInput | Prisma.active_sessionsScalarWhereInput[]
}

export type active_sessionsCreateWithoutRefresh_tokensInput = {
  id?: string
  access_token_jti: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutActive_sessionsInput
}

export type active_sessionsUncheckedCreateWithoutRefresh_tokensInput = {
  id?: string
  user_id: string
  access_token_jti: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
}

export type active_sessionsCreateOrConnectWithoutRefresh_tokensInput = {
  where: Prisma.active_sessionsWhereUniqueInput
  create: Prisma.XOR<Prisma.active_sessionsCreateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput>
}

export type active_sessionsCreateManyRefresh_tokensInputEnvelope = {
  data: Prisma.active_sessionsCreateManyRefresh_tokensInput | Prisma.active_sessionsCreateManyRefresh_tokensInput[]
  skipDuplicates?: boolean
}

export type active_sessionsUpsertWithWhereUniqueWithoutRefresh_tokensInput = {
  where: Prisma.active_sessionsWhereUniqueInput
  update: Prisma.XOR<Prisma.active_sessionsUpdateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedUpdateWithoutRefresh_tokensInput>
  create: Prisma.XOR<Prisma.active_sessionsCreateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedCreateWithoutRefresh_tokensInput>
}

export type active_sessionsUpdateWithWhereUniqueWithoutRefresh_tokensInput = {
  where: Prisma.active_sessionsWhereUniqueInput
  data: Prisma.XOR<Prisma.active_sessionsUpdateWithoutRefresh_tokensInput, Prisma.active_sessionsUncheckedUpdateWithoutRefresh_tokensInput>
}

export type active_sessionsUpdateManyWithWhereWithoutRefresh_tokensInput = {
  where: Prisma.active_sessionsScalarWhereInput
  data: Prisma.XOR<Prisma.active_sessionsUpdateManyMutationInput, Prisma.active_sessionsUncheckedUpdateManyWithoutRefresh_tokensInput>
}

export type active_sessionsScalarWhereInput = {
  AND?: Prisma.active_sessionsScalarWhereInput | Prisma.active_sessionsScalarWhereInput[]
  OR?: Prisma.active_sessionsScalarWhereInput[]
  NOT?: Prisma.active_sessionsScalarWhereInput | Prisma.active_sessionsScalarWhereInput[]
  id?: Prisma.UuidFilter<"active_sessions"> | string
  user_id?: Prisma.UuidFilter<"active_sessions"> | string
  access_token_jti?: Prisma.StringFilter<"active_sessions"> | string
  refresh_token_id?: Prisma.UuidFilter<"active_sessions"> | string
  device_name?: Prisma.StringNullableFilter<"active_sessions"> | string | null
  last_activity_at?: Prisma.DateTimeFilter<"active_sessions"> | Date | string
  expires_at?: Prisma.DateTimeFilter<"active_sessions"> | Date | string
  created_at?: Prisma.DateTimeNullableFilter<"active_sessions"> | Date | string | null
}

export type active_sessionsCreateWithoutUsersInput = {
  id?: string
  access_token_jti: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
  refresh_tokens: Prisma.refresh_tokensCreateNestedOneWithoutActive_sessionsInput
}

export type active_sessionsUncheckedCreateWithoutUsersInput = {
  id?: string
  access_token_jti: string
  refresh_token_id: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
}

export type active_sessionsCreateOrConnectWithoutUsersInput = {
  where: Prisma.active_sessionsWhereUniqueInput
  create: Prisma.XOR<Prisma.active_sessionsCreateWithoutUsersInput, Prisma.active_sessionsUncheckedCreateWithoutUsersInput>
}

export type active_sessionsCreateManyUsersInputEnvelope = {
  data: Prisma.active_sessionsCreateManyUsersInput | Prisma.active_sessionsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type active_sessionsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.active_sessionsWhereUniqueInput
  update: Prisma.XOR<Prisma.active_sessionsUpdateWithoutUsersInput, Prisma.active_sessionsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.active_sessionsCreateWithoutUsersInput, Prisma.active_sessionsUncheckedCreateWithoutUsersInput>
}

export type active_sessionsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.active_sessionsWhereUniqueInput
  data: Prisma.XOR<Prisma.active_sessionsUpdateWithoutUsersInput, Prisma.active_sessionsUncheckedUpdateWithoutUsersInput>
}

export type active_sessionsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.active_sessionsScalarWhereInput
  data: Prisma.XOR<Prisma.active_sessionsUpdateManyMutationInput, Prisma.active_sessionsUncheckedUpdateManyWithoutUsersInput>
}

export type active_sessionsCreateManyRefresh_tokensInput = {
  id?: string
  user_id: string
  access_token_jti: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
}

export type active_sessionsUpdateWithoutRefresh_tokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutActive_sessionsNestedInput
}

export type active_sessionsUncheckedUpdateWithoutRefresh_tokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type active_sessionsUncheckedUpdateManyWithoutRefresh_tokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type active_sessionsCreateManyUsersInput = {
  id?: string
  access_token_jti: string
  refresh_token_id: string
  device_name?: string | null
  last_activity_at: Date | string
  expires_at: Date | string
  created_at?: Date | string | null
}

export type active_sessionsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_tokens?: Prisma.refresh_tokensUpdateOneRequiredWithoutActive_sessionsNestedInput
}

export type active_sessionsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  refresh_token_id?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type active_sessionsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token_jti?: Prisma.StringFieldUpdateOperationsInput | string
  refresh_token_id?: Prisma.StringFieldUpdateOperationsInput | string
  device_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_activity_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type active_sessionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  access_token_jti?: boolean
  refresh_token_id?: boolean
  device_name?: boolean
  last_activity_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  refresh_tokens?: boolean | Prisma.refresh_tokensDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["active_sessions"]>

export type active_sessionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  access_token_jti?: boolean
  refresh_token_id?: boolean
  device_name?: boolean
  last_activity_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  refresh_tokens?: boolean | Prisma.refresh_tokensDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["active_sessions"]>

export type active_sessionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  access_token_jti?: boolean
  refresh_token_id?: boolean
  device_name?: boolean
  last_activity_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  refresh_tokens?: boolean | Prisma.refresh_tokensDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["active_sessions"]>

export type active_sessionsSelectScalar = {
  id?: boolean
  user_id?: boolean
  access_token_jti?: boolean
  refresh_token_id?: boolean
  device_name?: boolean
  last_activity_at?: boolean
  expires_at?: boolean
  created_at?: boolean
}

export type active_sessionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "access_token_jti" | "refresh_token_id" | "device_name" | "last_activity_at" | "expires_at" | "created_at", ExtArgs["result"]["active_sessions"]>
export type active_sessionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  refresh_tokens?: boolean | Prisma.refresh_tokensDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type active_sessionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  refresh_tokens?: boolean | Prisma.refresh_tokensDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type active_sessionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  refresh_tokens?: boolean | Prisma.refresh_tokensDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $active_sessionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "active_sessions"
  objects: {
    refresh_tokens: Prisma.$refresh_tokensPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    access_token_jti: string
    refresh_token_id: string
    device_name: string | null
    last_activity_at: Date
    expires_at: Date
    created_at: Date | null
  }, ExtArgs["result"]["active_sessions"]>
  composites: {}
}

export type active_sessionsGetPayload<S extends boolean | null | undefined | active_sessionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload, S>

export type active_sessionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<active_sessionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Active_sessionsCountAggregateInputType | true
  }

export interface active_sessionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['active_sessions'], meta: { name: 'active_sessions' } }
  /**
   * Find zero or one Active_sessions that matches the filter.
   * @param {active_sessionsFindUniqueArgs} args - Arguments to find a Active_sessions
   * @example
   * // Get one Active_sessions
   * const active_sessions = await prisma.active_sessions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends active_sessionsFindUniqueArgs>(args: Prisma.SelectSubset<T, active_sessionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Active_sessions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {active_sessionsFindUniqueOrThrowArgs} args - Arguments to find a Active_sessions
   * @example
   * // Get one Active_sessions
   * const active_sessions = await prisma.active_sessions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends active_sessionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, active_sessionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Active_sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {active_sessionsFindFirstArgs} args - Arguments to find a Active_sessions
   * @example
   * // Get one Active_sessions
   * const active_sessions = await prisma.active_sessions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends active_sessionsFindFirstArgs>(args?: Prisma.SelectSubset<T, active_sessionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Active_sessions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {active_sessionsFindFirstOrThrowArgs} args - Arguments to find a Active_sessions
   * @example
   * // Get one Active_sessions
   * const active_sessions = await prisma.active_sessions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends active_sessionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, active_sessionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Active_sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {active_sessionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Active_sessions
   * const active_sessions = await prisma.active_sessions.findMany()
   * 
   * // Get first 10 Active_sessions
   * const active_sessions = await prisma.active_sessions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const active_sessionsWithIdOnly = await prisma.active_sessions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends active_sessionsFindManyArgs>(args?: Prisma.SelectSubset<T, active_sessionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Active_sessions.
   * @param {active_sessionsCreateArgs} args - Arguments to create a Active_sessions.
   * @example
   * // Create one Active_sessions
   * const Active_sessions = await prisma.active_sessions.create({
   *   data: {
   *     // ... data to create a Active_sessions
   *   }
   * })
   * 
   */
  create<T extends active_sessionsCreateArgs>(args: Prisma.SelectSubset<T, active_sessionsCreateArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Active_sessions.
   * @param {active_sessionsCreateManyArgs} args - Arguments to create many Active_sessions.
   * @example
   * // Create many Active_sessions
   * const active_sessions = await prisma.active_sessions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends active_sessionsCreateManyArgs>(args?: Prisma.SelectSubset<T, active_sessionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Active_sessions and returns the data saved in the database.
   * @param {active_sessionsCreateManyAndReturnArgs} args - Arguments to create many Active_sessions.
   * @example
   * // Create many Active_sessions
   * const active_sessions = await prisma.active_sessions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Active_sessions and only return the `id`
   * const active_sessionsWithIdOnly = await prisma.active_sessions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends active_sessionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, active_sessionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Active_sessions.
   * @param {active_sessionsDeleteArgs} args - Arguments to delete one Active_sessions.
   * @example
   * // Delete one Active_sessions
   * const Active_sessions = await prisma.active_sessions.delete({
   *   where: {
   *     // ... filter to delete one Active_sessions
   *   }
   * })
   * 
   */
  delete<T extends active_sessionsDeleteArgs>(args: Prisma.SelectSubset<T, active_sessionsDeleteArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Active_sessions.
   * @param {active_sessionsUpdateArgs} args - Arguments to update one Active_sessions.
   * @example
   * // Update one Active_sessions
   * const active_sessions = await prisma.active_sessions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends active_sessionsUpdateArgs>(args: Prisma.SelectSubset<T, active_sessionsUpdateArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Active_sessions.
   * @param {active_sessionsDeleteManyArgs} args - Arguments to filter Active_sessions to delete.
   * @example
   * // Delete a few Active_sessions
   * const { count } = await prisma.active_sessions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends active_sessionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, active_sessionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Active_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {active_sessionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Active_sessions
   * const active_sessions = await prisma.active_sessions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends active_sessionsUpdateManyArgs>(args: Prisma.SelectSubset<T, active_sessionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Active_sessions and returns the data updated in the database.
   * @param {active_sessionsUpdateManyAndReturnArgs} args - Arguments to update many Active_sessions.
   * @example
   * // Update many Active_sessions
   * const active_sessions = await prisma.active_sessions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Active_sessions and only return the `id`
   * const active_sessionsWithIdOnly = await prisma.active_sessions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends active_sessionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, active_sessionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Active_sessions.
   * @param {active_sessionsUpsertArgs} args - Arguments to update or create a Active_sessions.
   * @example
   * // Update or create a Active_sessions
   * const active_sessions = await prisma.active_sessions.upsert({
   *   create: {
   *     // ... data to create a Active_sessions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Active_sessions we want to update
   *   }
   * })
   */
  upsert<T extends active_sessionsUpsertArgs>(args: Prisma.SelectSubset<T, active_sessionsUpsertArgs<ExtArgs>>): Prisma.Prisma__active_sessionsClient<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Active_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {active_sessionsCountArgs} args - Arguments to filter Active_sessions to count.
   * @example
   * // Count the number of Active_sessions
   * const count = await prisma.active_sessions.count({
   *   where: {
   *     // ... the filter for the Active_sessions we want to count
   *   }
   * })
  **/
  count<T extends active_sessionsCountArgs>(
    args?: Prisma.Subset<T, active_sessionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Active_sessionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Active_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Active_sessionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Active_sessionsAggregateArgs>(args: Prisma.Subset<T, Active_sessionsAggregateArgs>): Prisma.PrismaPromise<GetActive_sessionsAggregateType<T>>

  /**
   * Group by Active_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {active_sessionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends active_sessionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: active_sessionsGroupByArgs['orderBy'] }
      : { orderBy?: active_sessionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, active_sessionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActive_sessionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the active_sessions model
 */
readonly fields: active_sessionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for active_sessions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__active_sessionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  refresh_tokens<T extends Prisma.refresh_tokensDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.refresh_tokensDefaultArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the active_sessions model
 */
export interface active_sessionsFieldRefs {
  readonly id: Prisma.FieldRef<"active_sessions", 'String'>
  readonly user_id: Prisma.FieldRef<"active_sessions", 'String'>
  readonly access_token_jti: Prisma.FieldRef<"active_sessions", 'String'>
  readonly refresh_token_id: Prisma.FieldRef<"active_sessions", 'String'>
  readonly device_name: Prisma.FieldRef<"active_sessions", 'String'>
  readonly last_activity_at: Prisma.FieldRef<"active_sessions", 'DateTime'>
  readonly expires_at: Prisma.FieldRef<"active_sessions", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"active_sessions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * active_sessions findUnique
 */
export type active_sessionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * Filter, which active_sessions to fetch.
   */
  where: Prisma.active_sessionsWhereUniqueInput
}

/**
 * active_sessions findUniqueOrThrow
 */
export type active_sessionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * Filter, which active_sessions to fetch.
   */
  where: Prisma.active_sessionsWhereUniqueInput
}

/**
 * active_sessions findFirst
 */
export type active_sessionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * Filter, which active_sessions to fetch.
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of active_sessions to fetch.
   */
  orderBy?: Prisma.active_sessionsOrderByWithRelationInput | Prisma.active_sessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for active_sessions.
   */
  cursor?: Prisma.active_sessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` active_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` active_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of active_sessions.
   */
  distinct?: Prisma.Active_sessionsScalarFieldEnum | Prisma.Active_sessionsScalarFieldEnum[]
}

/**
 * active_sessions findFirstOrThrow
 */
export type active_sessionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * Filter, which active_sessions to fetch.
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of active_sessions to fetch.
   */
  orderBy?: Prisma.active_sessionsOrderByWithRelationInput | Prisma.active_sessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for active_sessions.
   */
  cursor?: Prisma.active_sessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` active_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` active_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of active_sessions.
   */
  distinct?: Prisma.Active_sessionsScalarFieldEnum | Prisma.Active_sessionsScalarFieldEnum[]
}

/**
 * active_sessions findMany
 */
export type active_sessionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * Filter, which active_sessions to fetch.
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of active_sessions to fetch.
   */
  orderBy?: Prisma.active_sessionsOrderByWithRelationInput | Prisma.active_sessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing active_sessions.
   */
  cursor?: Prisma.active_sessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` active_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` active_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of active_sessions.
   */
  distinct?: Prisma.Active_sessionsScalarFieldEnum | Prisma.Active_sessionsScalarFieldEnum[]
}

/**
 * active_sessions create
 */
export type active_sessionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * The data needed to create a active_sessions.
   */
  data: Prisma.XOR<Prisma.active_sessionsCreateInput, Prisma.active_sessionsUncheckedCreateInput>
}

/**
 * active_sessions createMany
 */
export type active_sessionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many active_sessions.
   */
  data: Prisma.active_sessionsCreateManyInput | Prisma.active_sessionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * active_sessions createManyAndReturn
 */
export type active_sessionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * The data used to create many active_sessions.
   */
  data: Prisma.active_sessionsCreateManyInput | Prisma.active_sessionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * active_sessions update
 */
export type active_sessionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * The data needed to update a active_sessions.
   */
  data: Prisma.XOR<Prisma.active_sessionsUpdateInput, Prisma.active_sessionsUncheckedUpdateInput>
  /**
   * Choose, which active_sessions to update.
   */
  where: Prisma.active_sessionsWhereUniqueInput
}

/**
 * active_sessions updateMany
 */
export type active_sessionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update active_sessions.
   */
  data: Prisma.XOR<Prisma.active_sessionsUpdateManyMutationInput, Prisma.active_sessionsUncheckedUpdateManyInput>
  /**
   * Filter which active_sessions to update
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * Limit how many active_sessions to update.
   */
  limit?: number
}

/**
 * active_sessions updateManyAndReturn
 */
export type active_sessionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * The data used to update active_sessions.
   */
  data: Prisma.XOR<Prisma.active_sessionsUpdateManyMutationInput, Prisma.active_sessionsUncheckedUpdateManyInput>
  /**
   * Filter which active_sessions to update
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * Limit how many active_sessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * active_sessions upsert
 */
export type active_sessionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * The filter to search for the active_sessions to update in case it exists.
   */
  where: Prisma.active_sessionsWhereUniqueInput
  /**
   * In case the active_sessions found by the `where` argument doesn't exist, create a new active_sessions with this data.
   */
  create: Prisma.XOR<Prisma.active_sessionsCreateInput, Prisma.active_sessionsUncheckedCreateInput>
  /**
   * In case the active_sessions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.active_sessionsUpdateInput, Prisma.active_sessionsUncheckedUpdateInput>
}

/**
 * active_sessions delete
 */
export type active_sessionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  /**
   * Filter which active_sessions to delete.
   */
  where: Prisma.active_sessionsWhereUniqueInput
}

/**
 * active_sessions deleteMany
 */
export type active_sessionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which active_sessions to delete
   */
  where?: Prisma.active_sessionsWhereInput
  /**
   * Limit how many active_sessions to delete.
   */
  limit?: number
}

/**
 * active_sessions without action
 */
export type active_sessionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
}
