
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `auth_audit_logs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model auth_audit_logs
 * 
 */
export type auth_audit_logsModel = runtime.Types.Result.DefaultSelection<Prisma.$auth_audit_logsPayload>

export type AggregateAuth_audit_logs = {
  _count: Auth_audit_logsCountAggregateOutputType | null
  _min: Auth_audit_logsMinAggregateOutputType | null
  _max: Auth_audit_logsMaxAggregateOutputType | null
}

export type Auth_audit_logsMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  event: $Enums.audit_event_type | null
  details: string | null
  created_at: Date | null
}

export type Auth_audit_logsMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  event: $Enums.audit_event_type | null
  details: string | null
  created_at: Date | null
}

export type Auth_audit_logsCountAggregateOutputType = {
  id: number
  user_id: number
  event: number
  details: number
  created_at: number
  _all: number
}


export type Auth_audit_logsMinAggregateInputType = {
  id?: true
  user_id?: true
  event?: true
  details?: true
  created_at?: true
}

export type Auth_audit_logsMaxAggregateInputType = {
  id?: true
  user_id?: true
  event?: true
  details?: true
  created_at?: true
}

export type Auth_audit_logsCountAggregateInputType = {
  id?: true
  user_id?: true
  event?: true
  details?: true
  created_at?: true
  _all?: true
}

export type Auth_audit_logsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which auth_audit_logs to aggregate.
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_audit_logs to fetch.
   */
  orderBy?: Prisma.auth_audit_logsOrderByWithRelationInput | Prisma.auth_audit_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.auth_audit_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_audit_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_audit_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned auth_audit_logs
  **/
  _count?: true | Auth_audit_logsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Auth_audit_logsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Auth_audit_logsMaxAggregateInputType
}

export type GetAuth_audit_logsAggregateType<T extends Auth_audit_logsAggregateArgs> = {
      [P in keyof T & keyof AggregateAuth_audit_logs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuth_audit_logs[P]>
    : Prisma.GetScalarType<T[P], AggregateAuth_audit_logs[P]>
}




export type auth_audit_logsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.auth_audit_logsWhereInput
  orderBy?: Prisma.auth_audit_logsOrderByWithAggregationInput | Prisma.auth_audit_logsOrderByWithAggregationInput[]
  by: Prisma.Auth_audit_logsScalarFieldEnum[] | Prisma.Auth_audit_logsScalarFieldEnum
  having?: Prisma.auth_audit_logsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Auth_audit_logsCountAggregateInputType | true
  _min?: Auth_audit_logsMinAggregateInputType
  _max?: Auth_audit_logsMaxAggregateInputType
}

export type Auth_audit_logsGroupByOutputType = {
  id: string
  user_id: string | null
  event: $Enums.audit_event_type
  details: string | null
  created_at: Date | null
  _count: Auth_audit_logsCountAggregateOutputType | null
  _min: Auth_audit_logsMinAggregateOutputType | null
  _max: Auth_audit_logsMaxAggregateOutputType | null
}

export type GetAuth_audit_logsGroupByPayload<T extends auth_audit_logsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Auth_audit_logsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Auth_audit_logsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Auth_audit_logsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Auth_audit_logsGroupByOutputType[P]>
      }
    >
  >



export type auth_audit_logsWhereInput = {
  AND?: Prisma.auth_audit_logsWhereInput | Prisma.auth_audit_logsWhereInput[]
  OR?: Prisma.auth_audit_logsWhereInput[]
  NOT?: Prisma.auth_audit_logsWhereInput | Prisma.auth_audit_logsWhereInput[]
  id?: Prisma.UuidFilter<"auth_audit_logs"> | string
  user_id?: Prisma.UuidNullableFilter<"auth_audit_logs"> | string | null
  event?: Prisma.Enumaudit_event_typeFilter<"auth_audit_logs"> | $Enums.audit_event_type
  details?: Prisma.StringNullableFilter<"auth_audit_logs"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"auth_audit_logs"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type auth_audit_logsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  event?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
}

export type auth_audit_logsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.auth_audit_logsWhereInput | Prisma.auth_audit_logsWhereInput[]
  OR?: Prisma.auth_audit_logsWhereInput[]
  NOT?: Prisma.auth_audit_logsWhereInput | Prisma.auth_audit_logsWhereInput[]
  user_id?: Prisma.UuidNullableFilter<"auth_audit_logs"> | string | null
  event?: Prisma.Enumaudit_event_typeFilter<"auth_audit_logs"> | $Enums.audit_event_type
  details?: Prisma.StringNullableFilter<"auth_audit_logs"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"auth_audit_logs"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "id">

export type auth_audit_logsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  event?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.auth_audit_logsCountOrderByAggregateInput
  _max?: Prisma.auth_audit_logsMaxOrderByAggregateInput
  _min?: Prisma.auth_audit_logsMinOrderByAggregateInput
}

export type auth_audit_logsScalarWhereWithAggregatesInput = {
  AND?: Prisma.auth_audit_logsScalarWhereWithAggregatesInput | Prisma.auth_audit_logsScalarWhereWithAggregatesInput[]
  OR?: Prisma.auth_audit_logsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.auth_audit_logsScalarWhereWithAggregatesInput | Prisma.auth_audit_logsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"auth_audit_logs"> | string
  user_id?: Prisma.UuidNullableWithAggregatesFilter<"auth_audit_logs"> | string | null
  event?: Prisma.Enumaudit_event_typeWithAggregatesFilter<"auth_audit_logs"> | $Enums.audit_event_type
  details?: Prisma.StringNullableWithAggregatesFilter<"auth_audit_logs"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"auth_audit_logs"> | Date | string | null
}

export type auth_audit_logsCreateInput = {
  id?: string
  event: $Enums.audit_event_type
  details?: string | null
  created_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutAuth_audit_logsInput
}

export type auth_audit_logsUncheckedCreateInput = {
  id?: string
  user_id?: string | null
  event: $Enums.audit_event_type
  details?: string | null
  created_at?: Date | string | null
}

export type auth_audit_logsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutAuth_audit_logsNestedInput
}

export type auth_audit_logsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type auth_audit_logsCreateManyInput = {
  id?: string
  user_id?: string | null
  event: $Enums.audit_event_type
  details?: string | null
  created_at?: Date | string | null
}

export type auth_audit_logsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type auth_audit_logsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type auth_audit_logsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type auth_audit_logsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type auth_audit_logsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type Auth_audit_logsListRelationFilter = {
  every?: Prisma.auth_audit_logsWhereInput
  some?: Prisma.auth_audit_logsWhereInput
  none?: Prisma.auth_audit_logsWhereInput
}

export type auth_audit_logsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Enumaudit_event_typeFieldUpdateOperationsInput = {
  set?: $Enums.audit_event_type
}

export type auth_audit_logsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.auth_audit_logsCreateWithoutUsersInput, Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput> | Prisma.auth_audit_logsCreateWithoutUsersInput[] | Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput | Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.auth_audit_logsCreateManyUsersInputEnvelope
  connect?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
}

export type auth_audit_logsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.auth_audit_logsCreateWithoutUsersInput, Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput> | Prisma.auth_audit_logsCreateWithoutUsersInput[] | Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput | Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.auth_audit_logsCreateManyUsersInputEnvelope
  connect?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
}

export type auth_audit_logsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.auth_audit_logsCreateWithoutUsersInput, Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput> | Prisma.auth_audit_logsCreateWithoutUsersInput[] | Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput | Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.auth_audit_logsUpsertWithWhereUniqueWithoutUsersInput | Prisma.auth_audit_logsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.auth_audit_logsCreateManyUsersInputEnvelope
  set?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  disconnect?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  delete?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  connect?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  update?: Prisma.auth_audit_logsUpdateWithWhereUniqueWithoutUsersInput | Prisma.auth_audit_logsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.auth_audit_logsUpdateManyWithWhereWithoutUsersInput | Prisma.auth_audit_logsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.auth_audit_logsScalarWhereInput | Prisma.auth_audit_logsScalarWhereInput[]
}

export type auth_audit_logsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.auth_audit_logsCreateWithoutUsersInput, Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput> | Prisma.auth_audit_logsCreateWithoutUsersInput[] | Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput | Prisma.auth_audit_logsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.auth_audit_logsUpsertWithWhereUniqueWithoutUsersInput | Prisma.auth_audit_logsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.auth_audit_logsCreateManyUsersInputEnvelope
  set?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  disconnect?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  delete?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  connect?: Prisma.auth_audit_logsWhereUniqueInput | Prisma.auth_audit_logsWhereUniqueInput[]
  update?: Prisma.auth_audit_logsUpdateWithWhereUniqueWithoutUsersInput | Prisma.auth_audit_logsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.auth_audit_logsUpdateManyWithWhereWithoutUsersInput | Prisma.auth_audit_logsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.auth_audit_logsScalarWhereInput | Prisma.auth_audit_logsScalarWhereInput[]
}

export type auth_audit_logsCreateWithoutUsersInput = {
  id?: string
  event: $Enums.audit_event_type
  details?: string | null
  created_at?: Date | string | null
}

export type auth_audit_logsUncheckedCreateWithoutUsersInput = {
  id?: string
  event: $Enums.audit_event_type
  details?: string | null
  created_at?: Date | string | null
}

export type auth_audit_logsCreateOrConnectWithoutUsersInput = {
  where: Prisma.auth_audit_logsWhereUniqueInput
  create: Prisma.XOR<Prisma.auth_audit_logsCreateWithoutUsersInput, Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput>
}

export type auth_audit_logsCreateManyUsersInputEnvelope = {
  data: Prisma.auth_audit_logsCreateManyUsersInput | Prisma.auth_audit_logsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type auth_audit_logsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.auth_audit_logsWhereUniqueInput
  update: Prisma.XOR<Prisma.auth_audit_logsUpdateWithoutUsersInput, Prisma.auth_audit_logsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.auth_audit_logsCreateWithoutUsersInput, Prisma.auth_audit_logsUncheckedCreateWithoutUsersInput>
}

export type auth_audit_logsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.auth_audit_logsWhereUniqueInput
  data: Prisma.XOR<Prisma.auth_audit_logsUpdateWithoutUsersInput, Prisma.auth_audit_logsUncheckedUpdateWithoutUsersInput>
}

export type auth_audit_logsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.auth_audit_logsScalarWhereInput
  data: Prisma.XOR<Prisma.auth_audit_logsUpdateManyMutationInput, Prisma.auth_audit_logsUncheckedUpdateManyWithoutUsersInput>
}

export type auth_audit_logsScalarWhereInput = {
  AND?: Prisma.auth_audit_logsScalarWhereInput | Prisma.auth_audit_logsScalarWhereInput[]
  OR?: Prisma.auth_audit_logsScalarWhereInput[]
  NOT?: Prisma.auth_audit_logsScalarWhereInput | Prisma.auth_audit_logsScalarWhereInput[]
  id?: Prisma.UuidFilter<"auth_audit_logs"> | string
  user_id?: Prisma.UuidNullableFilter<"auth_audit_logs"> | string | null
  event?: Prisma.Enumaudit_event_typeFilter<"auth_audit_logs"> | $Enums.audit_event_type
  details?: Prisma.StringNullableFilter<"auth_audit_logs"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"auth_audit_logs"> | Date | string | null
}

export type auth_audit_logsCreateManyUsersInput = {
  id?: string
  event: $Enums.audit_event_type
  details?: string | null
  created_at?: Date | string | null
}

export type auth_audit_logsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type auth_audit_logsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type auth_audit_logsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.Enumaudit_event_typeFieldUpdateOperationsInput | $Enums.audit_event_type
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type auth_audit_logsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  event?: boolean
  details?: boolean
  created_at?: boolean
  users?: boolean | Prisma.auth_audit_logs$usersArgs<ExtArgs>
}, ExtArgs["result"]["auth_audit_logs"]>

export type auth_audit_logsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  event?: boolean
  details?: boolean
  created_at?: boolean
  users?: boolean | Prisma.auth_audit_logs$usersArgs<ExtArgs>
}, ExtArgs["result"]["auth_audit_logs"]>

export type auth_audit_logsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  event?: boolean
  details?: boolean
  created_at?: boolean
  users?: boolean | Prisma.auth_audit_logs$usersArgs<ExtArgs>
}, ExtArgs["result"]["auth_audit_logs"]>

export type auth_audit_logsSelectScalar = {
  id?: boolean
  user_id?: boolean
  event?: boolean
  details?: boolean
  created_at?: boolean
}

export type auth_audit_logsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "event" | "details" | "created_at", ExtArgs["result"]["auth_audit_logs"]>
export type auth_audit_logsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.auth_audit_logs$usersArgs<ExtArgs>
}
export type auth_audit_logsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.auth_audit_logs$usersArgs<ExtArgs>
}
export type auth_audit_logsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.auth_audit_logs$usersArgs<ExtArgs>
}

export type $auth_audit_logsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "auth_audit_logs"
  objects: {
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string | null
    event: $Enums.audit_event_type
    details: string | null
    created_at: Date | null
  }, ExtArgs["result"]["auth_audit_logs"]>
  composites: {}
}

export type auth_audit_logsGetPayload<S extends boolean | null | undefined | auth_audit_logsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload, S>

export type auth_audit_logsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<auth_audit_logsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Auth_audit_logsCountAggregateInputType | true
  }

export interface auth_audit_logsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['auth_audit_logs'], meta: { name: 'auth_audit_logs' } }
  /**
   * Find zero or one Auth_audit_logs that matches the filter.
   * @param {auth_audit_logsFindUniqueArgs} args - Arguments to find a Auth_audit_logs
   * @example
   * // Get one Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends auth_audit_logsFindUniqueArgs>(args: Prisma.SelectSubset<T, auth_audit_logsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Auth_audit_logs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {auth_audit_logsFindUniqueOrThrowArgs} args - Arguments to find a Auth_audit_logs
   * @example
   * // Get one Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends auth_audit_logsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, auth_audit_logsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Auth_audit_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_audit_logsFindFirstArgs} args - Arguments to find a Auth_audit_logs
   * @example
   * // Get one Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends auth_audit_logsFindFirstArgs>(args?: Prisma.SelectSubset<T, auth_audit_logsFindFirstArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Auth_audit_logs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_audit_logsFindFirstOrThrowArgs} args - Arguments to find a Auth_audit_logs
   * @example
   * // Get one Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends auth_audit_logsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, auth_audit_logsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Auth_audit_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_audit_logsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.findMany()
   * 
   * // Get first 10 Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const auth_audit_logsWithIdOnly = await prisma.auth_audit_logs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends auth_audit_logsFindManyArgs>(args?: Prisma.SelectSubset<T, auth_audit_logsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Auth_audit_logs.
   * @param {auth_audit_logsCreateArgs} args - Arguments to create a Auth_audit_logs.
   * @example
   * // Create one Auth_audit_logs
   * const Auth_audit_logs = await prisma.auth_audit_logs.create({
   *   data: {
   *     // ... data to create a Auth_audit_logs
   *   }
   * })
   * 
   */
  create<T extends auth_audit_logsCreateArgs>(args: Prisma.SelectSubset<T, auth_audit_logsCreateArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Auth_audit_logs.
   * @param {auth_audit_logsCreateManyArgs} args - Arguments to create many Auth_audit_logs.
   * @example
   * // Create many Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends auth_audit_logsCreateManyArgs>(args?: Prisma.SelectSubset<T, auth_audit_logsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Auth_audit_logs and returns the data saved in the database.
   * @param {auth_audit_logsCreateManyAndReturnArgs} args - Arguments to create many Auth_audit_logs.
   * @example
   * // Create many Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Auth_audit_logs and only return the `id`
   * const auth_audit_logsWithIdOnly = await prisma.auth_audit_logs.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends auth_audit_logsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, auth_audit_logsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Auth_audit_logs.
   * @param {auth_audit_logsDeleteArgs} args - Arguments to delete one Auth_audit_logs.
   * @example
   * // Delete one Auth_audit_logs
   * const Auth_audit_logs = await prisma.auth_audit_logs.delete({
   *   where: {
   *     // ... filter to delete one Auth_audit_logs
   *   }
   * })
   * 
   */
  delete<T extends auth_audit_logsDeleteArgs>(args: Prisma.SelectSubset<T, auth_audit_logsDeleteArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Auth_audit_logs.
   * @param {auth_audit_logsUpdateArgs} args - Arguments to update one Auth_audit_logs.
   * @example
   * // Update one Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends auth_audit_logsUpdateArgs>(args: Prisma.SelectSubset<T, auth_audit_logsUpdateArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Auth_audit_logs.
   * @param {auth_audit_logsDeleteManyArgs} args - Arguments to filter Auth_audit_logs to delete.
   * @example
   * // Delete a few Auth_audit_logs
   * const { count } = await prisma.auth_audit_logs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends auth_audit_logsDeleteManyArgs>(args?: Prisma.SelectSubset<T, auth_audit_logsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Auth_audit_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_audit_logsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends auth_audit_logsUpdateManyArgs>(args: Prisma.SelectSubset<T, auth_audit_logsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Auth_audit_logs and returns the data updated in the database.
   * @param {auth_audit_logsUpdateManyAndReturnArgs} args - Arguments to update many Auth_audit_logs.
   * @example
   * // Update many Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Auth_audit_logs and only return the `id`
   * const auth_audit_logsWithIdOnly = await prisma.auth_audit_logs.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends auth_audit_logsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, auth_audit_logsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Auth_audit_logs.
   * @param {auth_audit_logsUpsertArgs} args - Arguments to update or create a Auth_audit_logs.
   * @example
   * // Update or create a Auth_audit_logs
   * const auth_audit_logs = await prisma.auth_audit_logs.upsert({
   *   create: {
   *     // ... data to create a Auth_audit_logs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Auth_audit_logs we want to update
   *   }
   * })
   */
  upsert<T extends auth_audit_logsUpsertArgs>(args: Prisma.SelectSubset<T, auth_audit_logsUpsertArgs<ExtArgs>>): Prisma.Prisma__auth_audit_logsClient<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Auth_audit_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_audit_logsCountArgs} args - Arguments to filter Auth_audit_logs to count.
   * @example
   * // Count the number of Auth_audit_logs
   * const count = await prisma.auth_audit_logs.count({
   *   where: {
   *     // ... the filter for the Auth_audit_logs we want to count
   *   }
   * })
  **/
  count<T extends auth_audit_logsCountArgs>(
    args?: Prisma.Subset<T, auth_audit_logsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Auth_audit_logsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Auth_audit_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Auth_audit_logsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Auth_audit_logsAggregateArgs>(args: Prisma.Subset<T, Auth_audit_logsAggregateArgs>): Prisma.PrismaPromise<GetAuth_audit_logsAggregateType<T>>

  /**
   * Group by Auth_audit_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_audit_logsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends auth_audit_logsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: auth_audit_logsGroupByArgs['orderBy'] }
      : { orderBy?: auth_audit_logsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, auth_audit_logsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuth_audit_logsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the auth_audit_logs model
 */
readonly fields: auth_audit_logsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for auth_audit_logs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__auth_audit_logsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.auth_audit_logs$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.auth_audit_logs$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the auth_audit_logs model
 */
export interface auth_audit_logsFieldRefs {
  readonly id: Prisma.FieldRef<"auth_audit_logs", 'String'>
  readonly user_id: Prisma.FieldRef<"auth_audit_logs", 'String'>
  readonly event: Prisma.FieldRef<"auth_audit_logs", 'audit_event_type'>
  readonly details: Prisma.FieldRef<"auth_audit_logs", 'String'>
  readonly created_at: Prisma.FieldRef<"auth_audit_logs", 'DateTime'>
}
    

// Custom InputTypes
/**
 * auth_audit_logs findUnique
 */
export type auth_audit_logsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * Filter, which auth_audit_logs to fetch.
   */
  where: Prisma.auth_audit_logsWhereUniqueInput
}

/**
 * auth_audit_logs findUniqueOrThrow
 */
export type auth_audit_logsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * Filter, which auth_audit_logs to fetch.
   */
  where: Prisma.auth_audit_logsWhereUniqueInput
}

/**
 * auth_audit_logs findFirst
 */
export type auth_audit_logsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * Filter, which auth_audit_logs to fetch.
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_audit_logs to fetch.
   */
  orderBy?: Prisma.auth_audit_logsOrderByWithRelationInput | Prisma.auth_audit_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for auth_audit_logs.
   */
  cursor?: Prisma.auth_audit_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_audit_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_audit_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of auth_audit_logs.
   */
  distinct?: Prisma.Auth_audit_logsScalarFieldEnum | Prisma.Auth_audit_logsScalarFieldEnum[]
}

/**
 * auth_audit_logs findFirstOrThrow
 */
export type auth_audit_logsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * Filter, which auth_audit_logs to fetch.
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_audit_logs to fetch.
   */
  orderBy?: Prisma.auth_audit_logsOrderByWithRelationInput | Prisma.auth_audit_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for auth_audit_logs.
   */
  cursor?: Prisma.auth_audit_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_audit_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_audit_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of auth_audit_logs.
   */
  distinct?: Prisma.Auth_audit_logsScalarFieldEnum | Prisma.Auth_audit_logsScalarFieldEnum[]
}

/**
 * auth_audit_logs findMany
 */
export type auth_audit_logsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * Filter, which auth_audit_logs to fetch.
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_audit_logs to fetch.
   */
  orderBy?: Prisma.auth_audit_logsOrderByWithRelationInput | Prisma.auth_audit_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing auth_audit_logs.
   */
  cursor?: Prisma.auth_audit_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_audit_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_audit_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of auth_audit_logs.
   */
  distinct?: Prisma.Auth_audit_logsScalarFieldEnum | Prisma.Auth_audit_logsScalarFieldEnum[]
}

/**
 * auth_audit_logs create
 */
export type auth_audit_logsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * The data needed to create a auth_audit_logs.
   */
  data: Prisma.XOR<Prisma.auth_audit_logsCreateInput, Prisma.auth_audit_logsUncheckedCreateInput>
}

/**
 * auth_audit_logs createMany
 */
export type auth_audit_logsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many auth_audit_logs.
   */
  data: Prisma.auth_audit_logsCreateManyInput | Prisma.auth_audit_logsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * auth_audit_logs createManyAndReturn
 */
export type auth_audit_logsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * The data used to create many auth_audit_logs.
   */
  data: Prisma.auth_audit_logsCreateManyInput | Prisma.auth_audit_logsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * auth_audit_logs update
 */
export type auth_audit_logsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * The data needed to update a auth_audit_logs.
   */
  data: Prisma.XOR<Prisma.auth_audit_logsUpdateInput, Prisma.auth_audit_logsUncheckedUpdateInput>
  /**
   * Choose, which auth_audit_logs to update.
   */
  where: Prisma.auth_audit_logsWhereUniqueInput
}

/**
 * auth_audit_logs updateMany
 */
export type auth_audit_logsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update auth_audit_logs.
   */
  data: Prisma.XOR<Prisma.auth_audit_logsUpdateManyMutationInput, Prisma.auth_audit_logsUncheckedUpdateManyInput>
  /**
   * Filter which auth_audit_logs to update
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * Limit how many auth_audit_logs to update.
   */
  limit?: number
}

/**
 * auth_audit_logs updateManyAndReturn
 */
export type auth_audit_logsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * The data used to update auth_audit_logs.
   */
  data: Prisma.XOR<Prisma.auth_audit_logsUpdateManyMutationInput, Prisma.auth_audit_logsUncheckedUpdateManyInput>
  /**
   * Filter which auth_audit_logs to update
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * Limit how many auth_audit_logs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * auth_audit_logs upsert
 */
export type auth_audit_logsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * The filter to search for the auth_audit_logs to update in case it exists.
   */
  where: Prisma.auth_audit_logsWhereUniqueInput
  /**
   * In case the auth_audit_logs found by the `where` argument doesn't exist, create a new auth_audit_logs with this data.
   */
  create: Prisma.XOR<Prisma.auth_audit_logsCreateInput, Prisma.auth_audit_logsUncheckedCreateInput>
  /**
   * In case the auth_audit_logs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.auth_audit_logsUpdateInput, Prisma.auth_audit_logsUncheckedUpdateInput>
}

/**
 * auth_audit_logs delete
 */
export type auth_audit_logsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  /**
   * Filter which auth_audit_logs to delete.
   */
  where: Prisma.auth_audit_logsWhereUniqueInput
}

/**
 * auth_audit_logs deleteMany
 */
export type auth_audit_logsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which auth_audit_logs to delete
   */
  where?: Prisma.auth_audit_logsWhereInput
  /**
   * Limit how many auth_audit_logs to delete.
   */
  limit?: number
}

/**
 * auth_audit_logs.users
 */
export type auth_audit_logs$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * auth_audit_logs without action
 */
export type auth_audit_logsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
}
