
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `otp_codes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model otp_codes
 * 
 */
export type otp_codesModel = runtime.Types.Result.DefaultSelection<Prisma.$otp_codesPayload>

export type AggregateOtp_codes = {
  _count: Otp_codesCountAggregateOutputType | null
  _avg: Otp_codesAvgAggregateOutputType | null
  _sum: Otp_codesSumAggregateOutputType | null
  _min: Otp_codesMinAggregateOutputType | null
  _max: Otp_codesMaxAggregateOutputType | null
}

export type Otp_codesAvgAggregateOutputType = {
  attempts: number | null
}

export type Otp_codesSumAggregateOutputType = {
  attempts: number | null
}

export type Otp_codesMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  code: string | null
  expires_at: Date | null
  is_used: boolean | null
  attempts: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type Otp_codesMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  code: string | null
  expires_at: Date | null
  is_used: boolean | null
  attempts: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type Otp_codesCountAggregateOutputType = {
  id: number
  user_id: number
  code: number
  expires_at: number
  is_used: number
  attempts: number
  created_at: number
  updated_at: number
  _all: number
}


export type Otp_codesAvgAggregateInputType = {
  attempts?: true
}

export type Otp_codesSumAggregateInputType = {
  attempts?: true
}

export type Otp_codesMinAggregateInputType = {
  id?: true
  user_id?: true
  code?: true
  expires_at?: true
  is_used?: true
  attempts?: true
  created_at?: true
  updated_at?: true
}

export type Otp_codesMaxAggregateInputType = {
  id?: true
  user_id?: true
  code?: true
  expires_at?: true
  is_used?: true
  attempts?: true
  created_at?: true
  updated_at?: true
}

export type Otp_codesCountAggregateInputType = {
  id?: true
  user_id?: true
  code?: true
  expires_at?: true
  is_used?: true
  attempts?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Otp_codesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which otp_codes to aggregate.
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of otp_codes to fetch.
   */
  orderBy?: Prisma.otp_codesOrderByWithRelationInput | Prisma.otp_codesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.otp_codesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` otp_codes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` otp_codes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned otp_codes
  **/
  _count?: true | Otp_codesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Otp_codesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Otp_codesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Otp_codesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Otp_codesMaxAggregateInputType
}

export type GetOtp_codesAggregateType<T extends Otp_codesAggregateArgs> = {
      [P in keyof T & keyof AggregateOtp_codes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOtp_codes[P]>
    : Prisma.GetScalarType<T[P], AggregateOtp_codes[P]>
}




export type otp_codesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.otp_codesWhereInput
  orderBy?: Prisma.otp_codesOrderByWithAggregationInput | Prisma.otp_codesOrderByWithAggregationInput[]
  by: Prisma.Otp_codesScalarFieldEnum[] | Prisma.Otp_codesScalarFieldEnum
  having?: Prisma.otp_codesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Otp_codesCountAggregateInputType | true
  _avg?: Otp_codesAvgAggregateInputType
  _sum?: Otp_codesSumAggregateInputType
  _min?: Otp_codesMinAggregateInputType
  _max?: Otp_codesMaxAggregateInputType
}

export type Otp_codesGroupByOutputType = {
  id: string
  user_id: string
  code: string
  expires_at: Date
  is_used: boolean | null
  attempts: number | null
  created_at: Date | null
  updated_at: Date | null
  _count: Otp_codesCountAggregateOutputType | null
  _avg: Otp_codesAvgAggregateOutputType | null
  _sum: Otp_codesSumAggregateOutputType | null
  _min: Otp_codesMinAggregateOutputType | null
  _max: Otp_codesMaxAggregateOutputType | null
}

export type GetOtp_codesGroupByPayload<T extends otp_codesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Otp_codesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Otp_codesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Otp_codesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Otp_codesGroupByOutputType[P]>
      }
    >
  >



export type otp_codesWhereInput = {
  AND?: Prisma.otp_codesWhereInput | Prisma.otp_codesWhereInput[]
  OR?: Prisma.otp_codesWhereInput[]
  NOT?: Prisma.otp_codesWhereInput | Prisma.otp_codesWhereInput[]
  id?: Prisma.UuidFilter<"otp_codes"> | string
  user_id?: Prisma.UuidFilter<"otp_codes"> | string
  code?: Prisma.StringFilter<"otp_codes"> | string
  expires_at?: Prisma.DateTimeFilter<"otp_codes"> | Date | string
  is_used?: Prisma.BoolNullableFilter<"otp_codes"> | boolean | null
  attempts?: Prisma.IntNullableFilter<"otp_codes"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"otp_codes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"otp_codes"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type otp_codesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  is_used?: Prisma.SortOrderInput | Prisma.SortOrder
  attempts?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
}

export type otp_codesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.otp_codesWhereInput | Prisma.otp_codesWhereInput[]
  OR?: Prisma.otp_codesWhereInput[]
  NOT?: Prisma.otp_codesWhereInput | Prisma.otp_codesWhereInput[]
  user_id?: Prisma.UuidFilter<"otp_codes"> | string
  code?: Prisma.StringFilter<"otp_codes"> | string
  expires_at?: Prisma.DateTimeFilter<"otp_codes"> | Date | string
  is_used?: Prisma.BoolNullableFilter<"otp_codes"> | boolean | null
  attempts?: Prisma.IntNullableFilter<"otp_codes"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"otp_codes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"otp_codes"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "id">

export type otp_codesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  is_used?: Prisma.SortOrderInput | Prisma.SortOrder
  attempts?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.otp_codesCountOrderByAggregateInput
  _avg?: Prisma.otp_codesAvgOrderByAggregateInput
  _max?: Prisma.otp_codesMaxOrderByAggregateInput
  _min?: Prisma.otp_codesMinOrderByAggregateInput
  _sum?: Prisma.otp_codesSumOrderByAggregateInput
}

export type otp_codesScalarWhereWithAggregatesInput = {
  AND?: Prisma.otp_codesScalarWhereWithAggregatesInput | Prisma.otp_codesScalarWhereWithAggregatesInput[]
  OR?: Prisma.otp_codesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.otp_codesScalarWhereWithAggregatesInput | Prisma.otp_codesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"otp_codes"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"otp_codes"> | string
  code?: Prisma.StringWithAggregatesFilter<"otp_codes"> | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"otp_codes"> | Date | string
  is_used?: Prisma.BoolNullableWithAggregatesFilter<"otp_codes"> | boolean | null
  attempts?: Prisma.IntNullableWithAggregatesFilter<"otp_codes"> | number | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"otp_codes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"otp_codes"> | Date | string | null
}

export type otp_codesCreateInput = {
  id?: string
  code: string
  expires_at: Date | string
  is_used?: boolean | null
  attempts?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutOtp_codesInput
}

export type otp_codesUncheckedCreateInput = {
  id?: string
  user_id: string
  code: string
  expires_at: Date | string
  is_used?: boolean | null
  attempts?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type otp_codesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutOtp_codesNestedInput
}

export type otp_codesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type otp_codesCreateManyInput = {
  id?: string
  user_id: string
  code: string
  expires_at: Date | string
  is_used?: boolean | null
  attempts?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type otp_codesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type otp_codesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type otp_codesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  is_used?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type otp_codesAvgOrderByAggregateInput = {
  attempts?: Prisma.SortOrder
}

export type otp_codesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  is_used?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type otp_codesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  is_used?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type otp_codesSumOrderByAggregateInput = {
  attempts?: Prisma.SortOrder
}

export type Otp_codesListRelationFilter = {
  every?: Prisma.otp_codesWhereInput
  some?: Prisma.otp_codesWhereInput
  none?: Prisma.otp_codesWhereInput
}

export type otp_codesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type otp_codesCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.otp_codesCreateWithoutUsersInput, Prisma.otp_codesUncheckedCreateWithoutUsersInput> | Prisma.otp_codesCreateWithoutUsersInput[] | Prisma.otp_codesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.otp_codesCreateOrConnectWithoutUsersInput | Prisma.otp_codesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.otp_codesCreateManyUsersInputEnvelope
  connect?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
}

export type otp_codesUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.otp_codesCreateWithoutUsersInput, Prisma.otp_codesUncheckedCreateWithoutUsersInput> | Prisma.otp_codesCreateWithoutUsersInput[] | Prisma.otp_codesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.otp_codesCreateOrConnectWithoutUsersInput | Prisma.otp_codesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.otp_codesCreateManyUsersInputEnvelope
  connect?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
}

export type otp_codesUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.otp_codesCreateWithoutUsersInput, Prisma.otp_codesUncheckedCreateWithoutUsersInput> | Prisma.otp_codesCreateWithoutUsersInput[] | Prisma.otp_codesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.otp_codesCreateOrConnectWithoutUsersInput | Prisma.otp_codesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.otp_codesUpsertWithWhereUniqueWithoutUsersInput | Prisma.otp_codesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.otp_codesCreateManyUsersInputEnvelope
  set?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  disconnect?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  delete?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  connect?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  update?: Prisma.otp_codesUpdateWithWhereUniqueWithoutUsersInput | Prisma.otp_codesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.otp_codesUpdateManyWithWhereWithoutUsersInput | Prisma.otp_codesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.otp_codesScalarWhereInput | Prisma.otp_codesScalarWhereInput[]
}

export type otp_codesUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.otp_codesCreateWithoutUsersInput, Prisma.otp_codesUncheckedCreateWithoutUsersInput> | Prisma.otp_codesCreateWithoutUsersInput[] | Prisma.otp_codesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.otp_codesCreateOrConnectWithoutUsersInput | Prisma.otp_codesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.otp_codesUpsertWithWhereUniqueWithoutUsersInput | Prisma.otp_codesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.otp_codesCreateManyUsersInputEnvelope
  set?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  disconnect?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  delete?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  connect?: Prisma.otp_codesWhereUniqueInput | Prisma.otp_codesWhereUniqueInput[]
  update?: Prisma.otp_codesUpdateWithWhereUniqueWithoutUsersInput | Prisma.otp_codesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.otp_codesUpdateManyWithWhereWithoutUsersInput | Prisma.otp_codesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.otp_codesScalarWhereInput | Prisma.otp_codesScalarWhereInput[]
}

export type otp_codesCreateWithoutUsersInput = {
  id?: string
  code: string
  expires_at: Date | string
  is_used?: boolean | null
  attempts?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type otp_codesUncheckedCreateWithoutUsersInput = {
  id?: string
  code: string
  expires_at: Date | string
  is_used?: boolean | null
  attempts?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type otp_codesCreateOrConnectWithoutUsersInput = {
  where: Prisma.otp_codesWhereUniqueInput
  create: Prisma.XOR<Prisma.otp_codesCreateWithoutUsersInput, Prisma.otp_codesUncheckedCreateWithoutUsersInput>
}

export type otp_codesCreateManyUsersInputEnvelope = {
  data: Prisma.otp_codesCreateManyUsersInput | Prisma.otp_codesCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type otp_codesUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.otp_codesWhereUniqueInput
  update: Prisma.XOR<Prisma.otp_codesUpdateWithoutUsersInput, Prisma.otp_codesUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.otp_codesCreateWithoutUsersInput, Prisma.otp_codesUncheckedCreateWithoutUsersInput>
}

export type otp_codesUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.otp_codesWhereUniqueInput
  data: Prisma.XOR<Prisma.otp_codesUpdateWithoutUsersInput, Prisma.otp_codesUncheckedUpdateWithoutUsersInput>
}

export type otp_codesUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.otp_codesScalarWhereInput
  data: Prisma.XOR<Prisma.otp_codesUpdateManyMutationInput, Prisma.otp_codesUncheckedUpdateManyWithoutUsersInput>
}

export type otp_codesScalarWhereInput = {
  AND?: Prisma.otp_codesScalarWhereInput | Prisma.otp_codesScalarWhereInput[]
  OR?: Prisma.otp_codesScalarWhereInput[]
  NOT?: Prisma.otp_codesScalarWhereInput | Prisma.otp_codesScalarWhereInput[]
  id?: Prisma.UuidFilter<"otp_codes"> | string
  user_id?: Prisma.UuidFilter<"otp_codes"> | string
  code?: Prisma.StringFilter<"otp_codes"> | string
  expires_at?: Prisma.DateTimeFilter<"otp_codes"> | Date | string
  is_used?: Prisma.BoolNullableFilter<"otp_codes"> | boolean | null
  attempts?: Prisma.IntNullableFilter<"otp_codes"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"otp_codes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"otp_codes"> | Date | string | null
}

export type otp_codesCreateManyUsersInput = {
  id?: string
  code: string
  expires_at: Date | string
  is_used?: boolean | null
  attempts?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type otp_codesUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type otp_codesUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type otp_codesUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_used?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type otp_codesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  code?: boolean
  expires_at?: boolean
  is_used?: boolean
  attempts?: boolean
  created_at?: boolean
  updated_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["otp_codes"]>

export type otp_codesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  code?: boolean
  expires_at?: boolean
  is_used?: boolean
  attempts?: boolean
  created_at?: boolean
  updated_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["otp_codes"]>

export type otp_codesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  code?: boolean
  expires_at?: boolean
  is_used?: boolean
  attempts?: boolean
  created_at?: boolean
  updated_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["otp_codes"]>

export type otp_codesSelectScalar = {
  id?: boolean
  user_id?: boolean
  code?: boolean
  expires_at?: boolean
  is_used?: boolean
  attempts?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type otp_codesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "code" | "expires_at" | "is_used" | "attempts" | "created_at" | "updated_at", ExtArgs["result"]["otp_codes"]>
export type otp_codesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type otp_codesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type otp_codesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $otp_codesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "otp_codes"
  objects: {
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    code: string
    expires_at: Date
    is_used: boolean | null
    attempts: number | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["otp_codes"]>
  composites: {}
}

export type otp_codesGetPayload<S extends boolean | null | undefined | otp_codesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$otp_codesPayload, S>

export type otp_codesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<otp_codesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Otp_codesCountAggregateInputType | true
  }

export interface otp_codesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['otp_codes'], meta: { name: 'otp_codes' } }
  /**
   * Find zero or one Otp_codes that matches the filter.
   * @param {otp_codesFindUniqueArgs} args - Arguments to find a Otp_codes
   * @example
   * // Get one Otp_codes
   * const otp_codes = await prisma.otp_codes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends otp_codesFindUniqueArgs>(args: Prisma.SelectSubset<T, otp_codesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Otp_codes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {otp_codesFindUniqueOrThrowArgs} args - Arguments to find a Otp_codes
   * @example
   * // Get one Otp_codes
   * const otp_codes = await prisma.otp_codes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends otp_codesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, otp_codesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Otp_codes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {otp_codesFindFirstArgs} args - Arguments to find a Otp_codes
   * @example
   * // Get one Otp_codes
   * const otp_codes = await prisma.otp_codes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends otp_codesFindFirstArgs>(args?: Prisma.SelectSubset<T, otp_codesFindFirstArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Otp_codes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {otp_codesFindFirstOrThrowArgs} args - Arguments to find a Otp_codes
   * @example
   * // Get one Otp_codes
   * const otp_codes = await prisma.otp_codes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends otp_codesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, otp_codesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Otp_codes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {otp_codesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Otp_codes
   * const otp_codes = await prisma.otp_codes.findMany()
   * 
   * // Get first 10 Otp_codes
   * const otp_codes = await prisma.otp_codes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const otp_codesWithIdOnly = await prisma.otp_codes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends otp_codesFindManyArgs>(args?: Prisma.SelectSubset<T, otp_codesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Otp_codes.
   * @param {otp_codesCreateArgs} args - Arguments to create a Otp_codes.
   * @example
   * // Create one Otp_codes
   * const Otp_codes = await prisma.otp_codes.create({
   *   data: {
   *     // ... data to create a Otp_codes
   *   }
   * })
   * 
   */
  create<T extends otp_codesCreateArgs>(args: Prisma.SelectSubset<T, otp_codesCreateArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Otp_codes.
   * @param {otp_codesCreateManyArgs} args - Arguments to create many Otp_codes.
   * @example
   * // Create many Otp_codes
   * const otp_codes = await prisma.otp_codes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends otp_codesCreateManyArgs>(args?: Prisma.SelectSubset<T, otp_codesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Otp_codes and returns the data saved in the database.
   * @param {otp_codesCreateManyAndReturnArgs} args - Arguments to create many Otp_codes.
   * @example
   * // Create many Otp_codes
   * const otp_codes = await prisma.otp_codes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Otp_codes and only return the `id`
   * const otp_codesWithIdOnly = await prisma.otp_codes.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends otp_codesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, otp_codesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Otp_codes.
   * @param {otp_codesDeleteArgs} args - Arguments to delete one Otp_codes.
   * @example
   * // Delete one Otp_codes
   * const Otp_codes = await prisma.otp_codes.delete({
   *   where: {
   *     // ... filter to delete one Otp_codes
   *   }
   * })
   * 
   */
  delete<T extends otp_codesDeleteArgs>(args: Prisma.SelectSubset<T, otp_codesDeleteArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Otp_codes.
   * @param {otp_codesUpdateArgs} args - Arguments to update one Otp_codes.
   * @example
   * // Update one Otp_codes
   * const otp_codes = await prisma.otp_codes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends otp_codesUpdateArgs>(args: Prisma.SelectSubset<T, otp_codesUpdateArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Otp_codes.
   * @param {otp_codesDeleteManyArgs} args - Arguments to filter Otp_codes to delete.
   * @example
   * // Delete a few Otp_codes
   * const { count } = await prisma.otp_codes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends otp_codesDeleteManyArgs>(args?: Prisma.SelectSubset<T, otp_codesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Otp_codes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {otp_codesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Otp_codes
   * const otp_codes = await prisma.otp_codes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends otp_codesUpdateManyArgs>(args: Prisma.SelectSubset<T, otp_codesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Otp_codes and returns the data updated in the database.
   * @param {otp_codesUpdateManyAndReturnArgs} args - Arguments to update many Otp_codes.
   * @example
   * // Update many Otp_codes
   * const otp_codes = await prisma.otp_codes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Otp_codes and only return the `id`
   * const otp_codesWithIdOnly = await prisma.otp_codes.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends otp_codesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, otp_codesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Otp_codes.
   * @param {otp_codesUpsertArgs} args - Arguments to update or create a Otp_codes.
   * @example
   * // Update or create a Otp_codes
   * const otp_codes = await prisma.otp_codes.upsert({
   *   create: {
   *     // ... data to create a Otp_codes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Otp_codes we want to update
   *   }
   * })
   */
  upsert<T extends otp_codesUpsertArgs>(args: Prisma.SelectSubset<T, otp_codesUpsertArgs<ExtArgs>>): Prisma.Prisma__otp_codesClient<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Otp_codes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {otp_codesCountArgs} args - Arguments to filter Otp_codes to count.
   * @example
   * // Count the number of Otp_codes
   * const count = await prisma.otp_codes.count({
   *   where: {
   *     // ... the filter for the Otp_codes we want to count
   *   }
   * })
  **/
  count<T extends otp_codesCountArgs>(
    args?: Prisma.Subset<T, otp_codesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Otp_codesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Otp_codes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Otp_codesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Otp_codesAggregateArgs>(args: Prisma.Subset<T, Otp_codesAggregateArgs>): Prisma.PrismaPromise<GetOtp_codesAggregateType<T>>

  /**
   * Group by Otp_codes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {otp_codesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends otp_codesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: otp_codesGroupByArgs['orderBy'] }
      : { orderBy?: otp_codesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, otp_codesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOtp_codesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the otp_codes model
 */
readonly fields: otp_codesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for otp_codes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__otp_codesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the otp_codes model
 */
export interface otp_codesFieldRefs {
  readonly id: Prisma.FieldRef<"otp_codes", 'String'>
  readonly user_id: Prisma.FieldRef<"otp_codes", 'String'>
  readonly code: Prisma.FieldRef<"otp_codes", 'String'>
  readonly expires_at: Prisma.FieldRef<"otp_codes", 'DateTime'>
  readonly is_used: Prisma.FieldRef<"otp_codes", 'Boolean'>
  readonly attempts: Prisma.FieldRef<"otp_codes", 'Int'>
  readonly created_at: Prisma.FieldRef<"otp_codes", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"otp_codes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * otp_codes findUnique
 */
export type otp_codesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * Filter, which otp_codes to fetch.
   */
  where: Prisma.otp_codesWhereUniqueInput
}

/**
 * otp_codes findUniqueOrThrow
 */
export type otp_codesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * Filter, which otp_codes to fetch.
   */
  where: Prisma.otp_codesWhereUniqueInput
}

/**
 * otp_codes findFirst
 */
export type otp_codesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * Filter, which otp_codes to fetch.
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of otp_codes to fetch.
   */
  orderBy?: Prisma.otp_codesOrderByWithRelationInput | Prisma.otp_codesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for otp_codes.
   */
  cursor?: Prisma.otp_codesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` otp_codes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` otp_codes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of otp_codes.
   */
  distinct?: Prisma.Otp_codesScalarFieldEnum | Prisma.Otp_codesScalarFieldEnum[]
}

/**
 * otp_codes findFirstOrThrow
 */
export type otp_codesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * Filter, which otp_codes to fetch.
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of otp_codes to fetch.
   */
  orderBy?: Prisma.otp_codesOrderByWithRelationInput | Prisma.otp_codesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for otp_codes.
   */
  cursor?: Prisma.otp_codesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` otp_codes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` otp_codes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of otp_codes.
   */
  distinct?: Prisma.Otp_codesScalarFieldEnum | Prisma.Otp_codesScalarFieldEnum[]
}

/**
 * otp_codes findMany
 */
export type otp_codesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * Filter, which otp_codes to fetch.
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of otp_codes to fetch.
   */
  orderBy?: Prisma.otp_codesOrderByWithRelationInput | Prisma.otp_codesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing otp_codes.
   */
  cursor?: Prisma.otp_codesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` otp_codes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` otp_codes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of otp_codes.
   */
  distinct?: Prisma.Otp_codesScalarFieldEnum | Prisma.Otp_codesScalarFieldEnum[]
}

/**
 * otp_codes create
 */
export type otp_codesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * The data needed to create a otp_codes.
   */
  data: Prisma.XOR<Prisma.otp_codesCreateInput, Prisma.otp_codesUncheckedCreateInput>
}

/**
 * otp_codes createMany
 */
export type otp_codesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many otp_codes.
   */
  data: Prisma.otp_codesCreateManyInput | Prisma.otp_codesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * otp_codes createManyAndReturn
 */
export type otp_codesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * The data used to create many otp_codes.
   */
  data: Prisma.otp_codesCreateManyInput | Prisma.otp_codesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * otp_codes update
 */
export type otp_codesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * The data needed to update a otp_codes.
   */
  data: Prisma.XOR<Prisma.otp_codesUpdateInput, Prisma.otp_codesUncheckedUpdateInput>
  /**
   * Choose, which otp_codes to update.
   */
  where: Prisma.otp_codesWhereUniqueInput
}

/**
 * otp_codes updateMany
 */
export type otp_codesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update otp_codes.
   */
  data: Prisma.XOR<Prisma.otp_codesUpdateManyMutationInput, Prisma.otp_codesUncheckedUpdateManyInput>
  /**
   * Filter which otp_codes to update
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * Limit how many otp_codes to update.
   */
  limit?: number
}

/**
 * otp_codes updateManyAndReturn
 */
export type otp_codesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * The data used to update otp_codes.
   */
  data: Prisma.XOR<Prisma.otp_codesUpdateManyMutationInput, Prisma.otp_codesUncheckedUpdateManyInput>
  /**
   * Filter which otp_codes to update
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * Limit how many otp_codes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * otp_codes upsert
 */
export type otp_codesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * The filter to search for the otp_codes to update in case it exists.
   */
  where: Prisma.otp_codesWhereUniqueInput
  /**
   * In case the otp_codes found by the `where` argument doesn't exist, create a new otp_codes with this data.
   */
  create: Prisma.XOR<Prisma.otp_codesCreateInput, Prisma.otp_codesUncheckedCreateInput>
  /**
   * In case the otp_codes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.otp_codesUpdateInput, Prisma.otp_codesUncheckedUpdateInput>
}

/**
 * otp_codes delete
 */
export type otp_codesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  /**
   * Filter which otp_codes to delete.
   */
  where: Prisma.otp_codesWhereUniqueInput
}

/**
 * otp_codes deleteMany
 */
export type otp_codesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which otp_codes to delete
   */
  where?: Prisma.otp_codesWhereInput
  /**
   * Limit how many otp_codes to delete.
   */
  limit?: number
}

/**
 * otp_codes without action
 */
export type otp_codesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
}
