
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `persons` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model persons
 * 
 */
export type personsModel = runtime.Types.Result.DefaultSelection<Prisma.$personsPayload>

export type AggregatePersons = {
  _count: PersonsCountAggregateOutputType | null
  _min: PersonsMinAggregateOutputType | null
  _max: PersonsMaxAggregateOutputType | null
}

export type PersonsMinAggregateOutputType = {
  id: string | null
  first_name: string | null
  paternal_last_name: string | null
  maternal_last_name: string | null
  birth_date: Date | null
  gender: $Enums.gender_type | null
  address: string | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type PersonsMaxAggregateOutputType = {
  id: string | null
  first_name: string | null
  paternal_last_name: string | null
  maternal_last_name: string | null
  birth_date: Date | null
  gender: $Enums.gender_type | null
  address: string | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type PersonsCountAggregateOutputType = {
  id: number
  first_name: number
  paternal_last_name: number
  maternal_last_name: number
  birth_date: number
  gender: number
  address: number
  created_at: number
  updated_at: number
  deleted_at: number
  _all: number
}


export type PersonsMinAggregateInputType = {
  id?: true
  first_name?: true
  paternal_last_name?: true
  maternal_last_name?: true
  birth_date?: true
  gender?: true
  address?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type PersonsMaxAggregateInputType = {
  id?: true
  first_name?: true
  paternal_last_name?: true
  maternal_last_name?: true
  birth_date?: true
  gender?: true
  address?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type PersonsCountAggregateInputType = {
  id?: true
  first_name?: true
  paternal_last_name?: true
  maternal_last_name?: true
  birth_date?: true
  gender?: true
  address?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  _all?: true
}

export type PersonsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which persons to aggregate.
   */
  where?: Prisma.personsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of persons to fetch.
   */
  orderBy?: Prisma.personsOrderByWithRelationInput | Prisma.personsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.personsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` persons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` persons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned persons
  **/
  _count?: true | PersonsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PersonsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PersonsMaxAggregateInputType
}

export type GetPersonsAggregateType<T extends PersonsAggregateArgs> = {
      [P in keyof T & keyof AggregatePersons]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePersons[P]>
    : Prisma.GetScalarType<T[P], AggregatePersons[P]>
}




export type personsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.personsWhereInput
  orderBy?: Prisma.personsOrderByWithAggregationInput | Prisma.personsOrderByWithAggregationInput[]
  by: Prisma.PersonsScalarFieldEnum[] | Prisma.PersonsScalarFieldEnum
  having?: Prisma.personsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PersonsCountAggregateInputType | true
  _min?: PersonsMinAggregateInputType
  _max?: PersonsMaxAggregateInputType
}

export type PersonsGroupByOutputType = {
  id: string
  first_name: string
  paternal_last_name: string
  maternal_last_name: string | null
  birth_date: Date | null
  gender: $Enums.gender_type
  address: string | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
  _count: PersonsCountAggregateOutputType | null
  _min: PersonsMinAggregateOutputType | null
  _max: PersonsMaxAggregateOutputType | null
}

export type GetPersonsGroupByPayload<T extends personsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PersonsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PersonsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PersonsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PersonsGroupByOutputType[P]>
      }
    >
  >



export type personsWhereInput = {
  AND?: Prisma.personsWhereInput | Prisma.personsWhereInput[]
  OR?: Prisma.personsWhereInput[]
  NOT?: Prisma.personsWhereInput | Prisma.personsWhereInput[]
  id?: Prisma.UuidFilter<"persons"> | string
  first_name?: Prisma.StringFilter<"persons"> | string
  paternal_last_name?: Prisma.StringFilter<"persons"> | string
  maternal_last_name?: Prisma.StringNullableFilter<"persons"> | string | null
  birth_date?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  gender?: Prisma.Enumgender_typeFilter<"persons"> | $Enums.gender_type
  address?: Prisma.StringNullableFilter<"persons"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  users?: Prisma.UsersListRelationFilter
}

export type personsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  first_name?: Prisma.SortOrder
  paternal_last_name?: Prisma.SortOrder
  maternal_last_name?: Prisma.SortOrderInput | Prisma.SortOrder
  birth_date?: Prisma.SortOrderInput | Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.usersOrderByRelationAggregateInput
}

export type personsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.personsWhereInput | Prisma.personsWhereInput[]
  OR?: Prisma.personsWhereInput[]
  NOT?: Prisma.personsWhereInput | Prisma.personsWhereInput[]
  first_name?: Prisma.StringFilter<"persons"> | string
  paternal_last_name?: Prisma.StringFilter<"persons"> | string
  maternal_last_name?: Prisma.StringNullableFilter<"persons"> | string | null
  birth_date?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  gender?: Prisma.Enumgender_typeFilter<"persons"> | $Enums.gender_type
  address?: Prisma.StringNullableFilter<"persons"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"persons"> | Date | string | null
  users?: Prisma.UsersListRelationFilter
}, "id">

export type personsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  first_name?: Prisma.SortOrder
  paternal_last_name?: Prisma.SortOrder
  maternal_last_name?: Prisma.SortOrderInput | Prisma.SortOrder
  birth_date?: Prisma.SortOrderInput | Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.personsCountOrderByAggregateInput
  _max?: Prisma.personsMaxOrderByAggregateInput
  _min?: Prisma.personsMinOrderByAggregateInput
}

export type personsScalarWhereWithAggregatesInput = {
  AND?: Prisma.personsScalarWhereWithAggregatesInput | Prisma.personsScalarWhereWithAggregatesInput[]
  OR?: Prisma.personsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.personsScalarWhereWithAggregatesInput | Prisma.personsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"persons"> | string
  first_name?: Prisma.StringWithAggregatesFilter<"persons"> | string
  paternal_last_name?: Prisma.StringWithAggregatesFilter<"persons"> | string
  maternal_last_name?: Prisma.StringNullableWithAggregatesFilter<"persons"> | string | null
  birth_date?: Prisma.DateTimeNullableWithAggregatesFilter<"persons"> | Date | string | null
  gender?: Prisma.Enumgender_typeWithAggregatesFilter<"persons"> | $Enums.gender_type
  address?: Prisma.StringNullableWithAggregatesFilter<"persons"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"persons"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"persons"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"persons"> | Date | string | null
}

export type personsCreateInput = {
  id?: string
  first_name: string
  paternal_last_name: string
  maternal_last_name?: string | null
  birth_date?: Date | string | null
  gender: $Enums.gender_type
  address?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  users?: Prisma.usersCreateNestedManyWithoutPersonsInput
}

export type personsUncheckedCreateInput = {
  id?: string
  first_name: string
  paternal_last_name: string
  maternal_last_name?: string | null
  birth_date?: Date | string | null
  gender: $Enums.gender_type
  address?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  users?: Prisma.usersUncheckedCreateNestedManyWithoutPersonsInput
}

export type personsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  first_name?: Prisma.StringFieldUpdateOperationsInput | string
  paternal_last_name?: Prisma.StringFieldUpdateOperationsInput | string
  maternal_last_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.Enumgender_typeFieldUpdateOperationsInput | $Enums.gender_type
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateManyWithoutPersonsNestedInput
}

export type personsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  first_name?: Prisma.StringFieldUpdateOperationsInput | string
  paternal_last_name?: Prisma.StringFieldUpdateOperationsInput | string
  maternal_last_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.Enumgender_typeFieldUpdateOperationsInput | $Enums.gender_type
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUncheckedUpdateManyWithoutPersonsNestedInput
}

export type personsCreateManyInput = {
  id?: string
  first_name: string
  paternal_last_name: string
  maternal_last_name?: string | null
  birth_date?: Date | string | null
  gender: $Enums.gender_type
  address?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
}

export type personsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  first_name?: Prisma.StringFieldUpdateOperationsInput | string
  paternal_last_name?: Prisma.StringFieldUpdateOperationsInput | string
  maternal_last_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.Enumgender_typeFieldUpdateOperationsInput | $Enums.gender_type
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type personsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  first_name?: Prisma.StringFieldUpdateOperationsInput | string
  paternal_last_name?: Prisma.StringFieldUpdateOperationsInput | string
  maternal_last_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.Enumgender_typeFieldUpdateOperationsInput | $Enums.gender_type
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type personsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  first_name?: Prisma.SortOrder
  paternal_last_name?: Prisma.SortOrder
  maternal_last_name?: Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type personsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  first_name?: Prisma.SortOrder
  paternal_last_name?: Prisma.SortOrder
  maternal_last_name?: Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type personsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  first_name?: Prisma.SortOrder
  paternal_last_name?: Prisma.SortOrder
  maternal_last_name?: Prisma.SortOrder
  birth_date?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type PersonsScalarRelationFilter = {
  is?: Prisma.personsWhereInput
  isNot?: Prisma.personsWhereInput
}

export type Enumgender_typeFieldUpdateOperationsInput = {
  set?: $Enums.gender_type
}

export type personsCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.personsCreateWithoutUsersInput, Prisma.personsUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.personsCreateOrConnectWithoutUsersInput
  connect?: Prisma.personsWhereUniqueInput
}

export type personsUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.personsCreateWithoutUsersInput, Prisma.personsUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.personsCreateOrConnectWithoutUsersInput
  upsert?: Prisma.personsUpsertWithoutUsersInput
  connect?: Prisma.personsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.personsUpdateToOneWithWhereWithoutUsersInput, Prisma.personsUpdateWithoutUsersInput>, Prisma.personsUncheckedUpdateWithoutUsersInput>
}

export type personsCreateWithoutUsersInput = {
  id?: string
  first_name: string
  paternal_last_name: string
  maternal_last_name?: string | null
  birth_date?: Date | string | null
  gender: $Enums.gender_type
  address?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
}

export type personsUncheckedCreateWithoutUsersInput = {
  id?: string
  first_name: string
  paternal_last_name: string
  maternal_last_name?: string | null
  birth_date?: Date | string | null
  gender: $Enums.gender_type
  address?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
}

export type personsCreateOrConnectWithoutUsersInput = {
  where: Prisma.personsWhereUniqueInput
  create: Prisma.XOR<Prisma.personsCreateWithoutUsersInput, Prisma.personsUncheckedCreateWithoutUsersInput>
}

export type personsUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.personsUpdateWithoutUsersInput, Prisma.personsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.personsCreateWithoutUsersInput, Prisma.personsUncheckedCreateWithoutUsersInput>
  where?: Prisma.personsWhereInput
}

export type personsUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.personsWhereInput
  data: Prisma.XOR<Prisma.personsUpdateWithoutUsersInput, Prisma.personsUncheckedUpdateWithoutUsersInput>
}

export type personsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  first_name?: Prisma.StringFieldUpdateOperationsInput | string
  paternal_last_name?: Prisma.StringFieldUpdateOperationsInput | string
  maternal_last_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.Enumgender_typeFieldUpdateOperationsInput | $Enums.gender_type
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type personsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  first_name?: Prisma.StringFieldUpdateOperationsInput | string
  paternal_last_name?: Prisma.StringFieldUpdateOperationsInput | string
  maternal_last_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  birth_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.Enumgender_typeFieldUpdateOperationsInput | $Enums.gender_type
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type PersonsCountOutputType
 */

export type PersonsCountOutputType = {
  users: number
}

export type PersonsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | PersonsCountOutputTypeCountUsersArgs
}

/**
 * PersonsCountOutputType without action
 */
export type PersonsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonsCountOutputType
   */
  select?: Prisma.PersonsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PersonsCountOutputType without action
 */
export type PersonsCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.usersWhereInput
}


export type personsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  first_name?: boolean
  paternal_last_name?: boolean
  maternal_last_name?: boolean
  birth_date?: boolean
  gender?: boolean
  address?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  users?: boolean | Prisma.persons$usersArgs<ExtArgs>
  _count?: boolean | Prisma.PersonsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["persons"]>

export type personsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  first_name?: boolean
  paternal_last_name?: boolean
  maternal_last_name?: boolean
  birth_date?: boolean
  gender?: boolean
  address?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["persons"]>

export type personsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  first_name?: boolean
  paternal_last_name?: boolean
  maternal_last_name?: boolean
  birth_date?: boolean
  gender?: boolean
  address?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["persons"]>

export type personsSelectScalar = {
  id?: boolean
  first_name?: boolean
  paternal_last_name?: boolean
  maternal_last_name?: boolean
  birth_date?: boolean
  gender?: boolean
  address?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}

export type personsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "first_name" | "paternal_last_name" | "maternal_last_name" | "birth_date" | "gender" | "address" | "created_at" | "updated_at" | "deleted_at", ExtArgs["result"]["persons"]>
export type personsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.persons$usersArgs<ExtArgs>
  _count?: boolean | Prisma.PersonsCountOutputTypeDefaultArgs<ExtArgs>
}
export type personsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type personsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $personsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "persons"
  objects: {
    users: Prisma.$usersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    first_name: string
    paternal_last_name: string
    maternal_last_name: string | null
    birth_date: Date | null
    gender: $Enums.gender_type
    address: string | null
    created_at: Date | null
    updated_at: Date | null
    deleted_at: Date | null
  }, ExtArgs["result"]["persons"]>
  composites: {}
}

export type personsGetPayload<S extends boolean | null | undefined | personsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$personsPayload, S>

export type personsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<personsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PersonsCountAggregateInputType | true
  }

export interface personsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['persons'], meta: { name: 'persons' } }
  /**
   * Find zero or one Persons that matches the filter.
   * @param {personsFindUniqueArgs} args - Arguments to find a Persons
   * @example
   * // Get one Persons
   * const persons = await prisma.persons.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends personsFindUniqueArgs>(args: Prisma.SelectSubset<T, personsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Persons that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {personsFindUniqueOrThrowArgs} args - Arguments to find a Persons
   * @example
   * // Get one Persons
   * const persons = await prisma.persons.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends personsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, personsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Persons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {personsFindFirstArgs} args - Arguments to find a Persons
   * @example
   * // Get one Persons
   * const persons = await prisma.persons.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends personsFindFirstArgs>(args?: Prisma.SelectSubset<T, personsFindFirstArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Persons that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {personsFindFirstOrThrowArgs} args - Arguments to find a Persons
   * @example
   * // Get one Persons
   * const persons = await prisma.persons.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends personsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, personsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Persons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {personsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Persons
   * const persons = await prisma.persons.findMany()
   * 
   * // Get first 10 Persons
   * const persons = await prisma.persons.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const personsWithIdOnly = await prisma.persons.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends personsFindManyArgs>(args?: Prisma.SelectSubset<T, personsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Persons.
   * @param {personsCreateArgs} args - Arguments to create a Persons.
   * @example
   * // Create one Persons
   * const Persons = await prisma.persons.create({
   *   data: {
   *     // ... data to create a Persons
   *   }
   * })
   * 
   */
  create<T extends personsCreateArgs>(args: Prisma.SelectSubset<T, personsCreateArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Persons.
   * @param {personsCreateManyArgs} args - Arguments to create many Persons.
   * @example
   * // Create many Persons
   * const persons = await prisma.persons.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends personsCreateManyArgs>(args?: Prisma.SelectSubset<T, personsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Persons and returns the data saved in the database.
   * @param {personsCreateManyAndReturnArgs} args - Arguments to create many Persons.
   * @example
   * // Create many Persons
   * const persons = await prisma.persons.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Persons and only return the `id`
   * const personsWithIdOnly = await prisma.persons.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends personsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, personsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Persons.
   * @param {personsDeleteArgs} args - Arguments to delete one Persons.
   * @example
   * // Delete one Persons
   * const Persons = await prisma.persons.delete({
   *   where: {
   *     // ... filter to delete one Persons
   *   }
   * })
   * 
   */
  delete<T extends personsDeleteArgs>(args: Prisma.SelectSubset<T, personsDeleteArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Persons.
   * @param {personsUpdateArgs} args - Arguments to update one Persons.
   * @example
   * // Update one Persons
   * const persons = await prisma.persons.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends personsUpdateArgs>(args: Prisma.SelectSubset<T, personsUpdateArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Persons.
   * @param {personsDeleteManyArgs} args - Arguments to filter Persons to delete.
   * @example
   * // Delete a few Persons
   * const { count } = await prisma.persons.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends personsDeleteManyArgs>(args?: Prisma.SelectSubset<T, personsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Persons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {personsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Persons
   * const persons = await prisma.persons.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends personsUpdateManyArgs>(args: Prisma.SelectSubset<T, personsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Persons and returns the data updated in the database.
   * @param {personsUpdateManyAndReturnArgs} args - Arguments to update many Persons.
   * @example
   * // Update many Persons
   * const persons = await prisma.persons.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Persons and only return the `id`
   * const personsWithIdOnly = await prisma.persons.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends personsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, personsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Persons.
   * @param {personsUpsertArgs} args - Arguments to update or create a Persons.
   * @example
   * // Update or create a Persons
   * const persons = await prisma.persons.upsert({
   *   create: {
   *     // ... data to create a Persons
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Persons we want to update
   *   }
   * })
   */
  upsert<T extends personsUpsertArgs>(args: Prisma.SelectSubset<T, personsUpsertArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Persons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {personsCountArgs} args - Arguments to filter Persons to count.
   * @example
   * // Count the number of Persons
   * const count = await prisma.persons.count({
   *   where: {
   *     // ... the filter for the Persons we want to count
   *   }
   * })
  **/
  count<T extends personsCountArgs>(
    args?: Prisma.Subset<T, personsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PersonsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Persons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PersonsAggregateArgs>(args: Prisma.Subset<T, PersonsAggregateArgs>): Prisma.PrismaPromise<GetPersonsAggregateType<T>>

  /**
   * Group by Persons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {personsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends personsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: personsGroupByArgs['orderBy'] }
      : { orderBy?: personsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, personsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPersonsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the persons model
 */
readonly fields: personsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for persons.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__personsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.persons$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.persons$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the persons model
 */
export interface personsFieldRefs {
  readonly id: Prisma.FieldRef<"persons", 'String'>
  readonly first_name: Prisma.FieldRef<"persons", 'String'>
  readonly paternal_last_name: Prisma.FieldRef<"persons", 'String'>
  readonly maternal_last_name: Prisma.FieldRef<"persons", 'String'>
  readonly birth_date: Prisma.FieldRef<"persons", 'DateTime'>
  readonly gender: Prisma.FieldRef<"persons", 'gender_type'>
  readonly address: Prisma.FieldRef<"persons", 'String'>
  readonly created_at: Prisma.FieldRef<"persons", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"persons", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"persons", 'DateTime'>
}
    

// Custom InputTypes
/**
 * persons findUnique
 */
export type personsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * Filter, which persons to fetch.
   */
  where: Prisma.personsWhereUniqueInput
}

/**
 * persons findUniqueOrThrow
 */
export type personsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * Filter, which persons to fetch.
   */
  where: Prisma.personsWhereUniqueInput
}

/**
 * persons findFirst
 */
export type personsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * Filter, which persons to fetch.
   */
  where?: Prisma.personsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of persons to fetch.
   */
  orderBy?: Prisma.personsOrderByWithRelationInput | Prisma.personsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for persons.
   */
  cursor?: Prisma.personsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` persons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` persons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of persons.
   */
  distinct?: Prisma.PersonsScalarFieldEnum | Prisma.PersonsScalarFieldEnum[]
}

/**
 * persons findFirstOrThrow
 */
export type personsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * Filter, which persons to fetch.
   */
  where?: Prisma.personsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of persons to fetch.
   */
  orderBy?: Prisma.personsOrderByWithRelationInput | Prisma.personsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for persons.
   */
  cursor?: Prisma.personsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` persons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` persons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of persons.
   */
  distinct?: Prisma.PersonsScalarFieldEnum | Prisma.PersonsScalarFieldEnum[]
}

/**
 * persons findMany
 */
export type personsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * Filter, which persons to fetch.
   */
  where?: Prisma.personsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of persons to fetch.
   */
  orderBy?: Prisma.personsOrderByWithRelationInput | Prisma.personsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing persons.
   */
  cursor?: Prisma.personsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` persons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` persons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of persons.
   */
  distinct?: Prisma.PersonsScalarFieldEnum | Prisma.PersonsScalarFieldEnum[]
}

/**
 * persons create
 */
export type personsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * The data needed to create a persons.
   */
  data: Prisma.XOR<Prisma.personsCreateInput, Prisma.personsUncheckedCreateInput>
}

/**
 * persons createMany
 */
export type personsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many persons.
   */
  data: Prisma.personsCreateManyInput | Prisma.personsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * persons createManyAndReturn
 */
export type personsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * The data used to create many persons.
   */
  data: Prisma.personsCreateManyInput | Prisma.personsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * persons update
 */
export type personsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * The data needed to update a persons.
   */
  data: Prisma.XOR<Prisma.personsUpdateInput, Prisma.personsUncheckedUpdateInput>
  /**
   * Choose, which persons to update.
   */
  where: Prisma.personsWhereUniqueInput
}

/**
 * persons updateMany
 */
export type personsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update persons.
   */
  data: Prisma.XOR<Prisma.personsUpdateManyMutationInput, Prisma.personsUncheckedUpdateManyInput>
  /**
   * Filter which persons to update
   */
  where?: Prisma.personsWhereInput
  /**
   * Limit how many persons to update.
   */
  limit?: number
}

/**
 * persons updateManyAndReturn
 */
export type personsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * The data used to update persons.
   */
  data: Prisma.XOR<Prisma.personsUpdateManyMutationInput, Prisma.personsUncheckedUpdateManyInput>
  /**
   * Filter which persons to update
   */
  where?: Prisma.personsWhereInput
  /**
   * Limit how many persons to update.
   */
  limit?: number
}

/**
 * persons upsert
 */
export type personsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * The filter to search for the persons to update in case it exists.
   */
  where: Prisma.personsWhereUniqueInput
  /**
   * In case the persons found by the `where` argument doesn't exist, create a new persons with this data.
   */
  create: Prisma.XOR<Prisma.personsCreateInput, Prisma.personsUncheckedCreateInput>
  /**
   * In case the persons was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.personsUpdateInput, Prisma.personsUncheckedUpdateInput>
}

/**
 * persons delete
 */
export type personsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
  /**
   * Filter which persons to delete.
   */
  where: Prisma.personsWhereUniqueInput
}

/**
 * persons deleteMany
 */
export type personsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which persons to delete
   */
  where?: Prisma.personsWhereInput
  /**
   * Limit how many persons to delete.
   */
  limit?: number
}

/**
 * persons.users
 */
export type persons$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  cursor?: Prisma.usersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * persons without action
 */
export type personsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the persons
   */
  select?: Prisma.personsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the persons
   */
  omit?: Prisma.personsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.personsInclude<ExtArgs> | null
}
