
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `users` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model users
 * 
 */
export type usersModel = runtime.Types.Result.DefaultSelection<Prisma.$usersPayload>

export type AggregateUsers = {
  _count: UsersCountAggregateOutputType | null
  _avg: UsersAvgAggregateOutputType | null
  _sum: UsersSumAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

export type UsersAvgAggregateOutputType = {
  failed_attempts: number | null
}

export type UsersSumAggregateOutputType = {
  failed_attempts: number | null
}

export type UsersMinAggregateOutputType = {
  id: string | null
  person_id: string | null
  email: string | null
  phone: string | null
  password_hash: string | null
  two_factor_method: boolean | null
  is_active: boolean | null
  failed_attempts: number | null
  blocked_until: Date | null
  last_login_at: Date | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type UsersMaxAggregateOutputType = {
  id: string | null
  person_id: string | null
  email: string | null
  phone: string | null
  password_hash: string | null
  two_factor_method: boolean | null
  is_active: boolean | null
  failed_attempts: number | null
  blocked_until: Date | null
  last_login_at: Date | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type UsersCountAggregateOutputType = {
  id: number
  person_id: number
  email: number
  phone: number
  password_hash: number
  two_factor_method: number
  is_active: number
  failed_attempts: number
  blocked_until: number
  last_login_at: number
  created_at: number
  updated_at: number
  deleted_at: number
  _all: number
}


export type UsersAvgAggregateInputType = {
  failed_attempts?: true
}

export type UsersSumAggregateInputType = {
  failed_attempts?: true
}

export type UsersMinAggregateInputType = {
  id?: true
  person_id?: true
  email?: true
  phone?: true
  password_hash?: true
  two_factor_method?: true
  is_active?: true
  failed_attempts?: true
  blocked_until?: true
  last_login_at?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type UsersMaxAggregateInputType = {
  id?: true
  person_id?: true
  email?: true
  phone?: true
  password_hash?: true
  two_factor_method?: true
  is_active?: true
  failed_attempts?: true
  blocked_until?: true
  last_login_at?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type UsersCountAggregateInputType = {
  id?: true
  person_id?: true
  email?: true
  phone?: true
  password_hash?: true
  two_factor_method?: true
  is_active?: true
  failed_attempts?: true
  blocked_until?: true
  last_login_at?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  _all?: true
}

export type UsersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which users to aggregate.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned users
  **/
  _count?: true | UsersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UsersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UsersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsersMaxAggregateInputType
}

export type GetUsersAggregateType<T extends UsersAggregateArgs> = {
      [P in keyof T & keyof AggregateUsers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsers[P]>
    : Prisma.GetScalarType<T[P], AggregateUsers[P]>
}




export type usersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.usersWhereInput
  orderBy?: Prisma.usersOrderByWithAggregationInput | Prisma.usersOrderByWithAggregationInput[]
  by: Prisma.UsersScalarFieldEnum[] | Prisma.UsersScalarFieldEnum
  having?: Prisma.usersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsersCountAggregateInputType | true
  _avg?: UsersAvgAggregateInputType
  _sum?: UsersSumAggregateInputType
  _min?: UsersMinAggregateInputType
  _max?: UsersMaxAggregateInputType
}

export type UsersGroupByOutputType = {
  id: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method: boolean | null
  is_active: boolean | null
  failed_attempts: number | null
  blocked_until: Date | null
  last_login_at: Date | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
  _count: UsersCountAggregateOutputType | null
  _avg: UsersAvgAggregateOutputType | null
  _sum: UsersSumAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

export type GetUsersGroupByPayload<T extends usersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
      }
    >
  >



export type usersWhereInput = {
  AND?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  OR?: Prisma.usersWhereInput[]
  NOT?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  id?: Prisma.UuidFilter<"users"> | string
  person_id?: Prisma.UuidFilter<"users"> | string
  email?: Prisma.StringFilter<"users"> | string
  phone?: Prisma.StringFilter<"users"> | string
  password_hash?: Prisma.StringFilter<"users"> | string
  two_factor_method?: Prisma.BoolNullableFilter<"users"> | boolean | null
  is_active?: Prisma.BoolNullableFilter<"users"> | boolean | null
  failed_attempts?: Prisma.IntNullableFilter<"users"> | number | null
  blocked_until?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  last_login_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  active_sessions?: Prisma.Active_sessionsListRelationFilter
  auth_audit_logs?: Prisma.Auth_audit_logsListRelationFilter
  otp_codes?: Prisma.Otp_codesListRelationFilter
  refresh_tokens?: Prisma.Refresh_tokensListRelationFilter
  persons?: Prisma.XOR<Prisma.PersonsScalarRelationFilter, Prisma.personsWhereInput>
}

export type usersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  person_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  two_factor_method?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrderInput | Prisma.SortOrder
  failed_attempts?: Prisma.SortOrderInput | Prisma.SortOrder
  blocked_until?: Prisma.SortOrderInput | Prisma.SortOrder
  last_login_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  active_sessions?: Prisma.active_sessionsOrderByRelationAggregateInput
  auth_audit_logs?: Prisma.auth_audit_logsOrderByRelationAggregateInput
  otp_codes?: Prisma.otp_codesOrderByRelationAggregateInput
  refresh_tokens?: Prisma.refresh_tokensOrderByRelationAggregateInput
  persons?: Prisma.personsOrderByWithRelationInput
}

export type usersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  phone?: string
  AND?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  OR?: Prisma.usersWhereInput[]
  NOT?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  person_id?: Prisma.UuidFilter<"users"> | string
  password_hash?: Prisma.StringFilter<"users"> | string
  two_factor_method?: Prisma.BoolNullableFilter<"users"> | boolean | null
  is_active?: Prisma.BoolNullableFilter<"users"> | boolean | null
  failed_attempts?: Prisma.IntNullableFilter<"users"> | number | null
  blocked_until?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  last_login_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  active_sessions?: Prisma.Active_sessionsListRelationFilter
  auth_audit_logs?: Prisma.Auth_audit_logsListRelationFilter
  otp_codes?: Prisma.Otp_codesListRelationFilter
  refresh_tokens?: Prisma.Refresh_tokensListRelationFilter
  persons?: Prisma.XOR<Prisma.PersonsScalarRelationFilter, Prisma.personsWhereInput>
}, "id" | "email" | "phone">

export type usersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  person_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  two_factor_method?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrderInput | Prisma.SortOrder
  failed_attempts?: Prisma.SortOrderInput | Prisma.SortOrder
  blocked_until?: Prisma.SortOrderInput | Prisma.SortOrder
  last_login_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.usersCountOrderByAggregateInput
  _avg?: Prisma.usersAvgOrderByAggregateInput
  _max?: Prisma.usersMaxOrderByAggregateInput
  _min?: Prisma.usersMinOrderByAggregateInput
  _sum?: Prisma.usersSumOrderByAggregateInput
}

export type usersScalarWhereWithAggregatesInput = {
  AND?: Prisma.usersScalarWhereWithAggregatesInput | Prisma.usersScalarWhereWithAggregatesInput[]
  OR?: Prisma.usersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.usersScalarWhereWithAggregatesInput | Prisma.usersScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"users"> | string
  person_id?: Prisma.UuidWithAggregatesFilter<"users"> | string
  email?: Prisma.StringWithAggregatesFilter<"users"> | string
  phone?: Prisma.StringWithAggregatesFilter<"users"> | string
  password_hash?: Prisma.StringWithAggregatesFilter<"users"> | string
  two_factor_method?: Prisma.BoolNullableWithAggregatesFilter<"users"> | boolean | null
  is_active?: Prisma.BoolNullableWithAggregatesFilter<"users"> | boolean | null
  failed_attempts?: Prisma.IntNullableWithAggregatesFilter<"users"> | number | null
  blocked_until?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
  last_login_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
}

export type usersCreateInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensCreateNestedManyWithoutUsersInput
  persons: Prisma.personsCreateNestedOneWithoutUsersInput
}

export type usersUncheckedCreateInput = {
  id?: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesUncheckedCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedCreateNestedManyWithoutUsersInput
}

export type usersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUpdateManyWithoutUsersNestedInput
  persons?: Prisma.personsUpdateOneRequiredWithoutUsersNestedInput
}

export type usersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  person_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUncheckedUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateManyInput = {
  id?: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
}

export type usersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type usersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  person_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UsersScalarRelationFilter = {
  is?: Prisma.usersWhereInput
  isNot?: Prisma.usersWhereInput
}

export type UsersNullableScalarRelationFilter = {
  is?: Prisma.usersWhereInput | null
  isNot?: Prisma.usersWhereInput | null
}

export type UsersListRelationFilter = {
  every?: Prisma.usersWhereInput
  some?: Prisma.usersWhereInput
  none?: Prisma.usersWhereInput
}

export type usersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type usersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  person_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  two_factor_method?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  failed_attempts?: Prisma.SortOrder
  blocked_until?: Prisma.SortOrder
  last_login_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type usersAvgOrderByAggregateInput = {
  failed_attempts?: Prisma.SortOrder
}

export type usersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  person_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  two_factor_method?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  failed_attempts?: Prisma.SortOrder
  blocked_until?: Prisma.SortOrder
  last_login_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type usersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  person_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  two_factor_method?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  failed_attempts?: Prisma.SortOrder
  blocked_until?: Prisma.SortOrder
  last_login_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type usersSumOrderByAggregateInput = {
  failed_attempts?: Prisma.SortOrder
}

export type usersCreateNestedOneWithoutActive_sessionsInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutActive_sessionsInput, Prisma.usersUncheckedCreateWithoutActive_sessionsInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutActive_sessionsInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneRequiredWithoutActive_sessionsNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutActive_sessionsInput, Prisma.usersUncheckedCreateWithoutActive_sessionsInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutActive_sessionsInput
  upsert?: Prisma.usersUpsertWithoutActive_sessionsInput
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutActive_sessionsInput, Prisma.usersUpdateWithoutActive_sessionsInput>, Prisma.usersUncheckedUpdateWithoutActive_sessionsInput>
}

export type usersCreateNestedOneWithoutAuth_audit_logsInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutAuth_audit_logsInput, Prisma.usersUncheckedCreateWithoutAuth_audit_logsInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutAuth_audit_logsInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneWithoutAuth_audit_logsNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutAuth_audit_logsInput, Prisma.usersUncheckedCreateWithoutAuth_audit_logsInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutAuth_audit_logsInput
  upsert?: Prisma.usersUpsertWithoutAuth_audit_logsInput
  disconnect?: Prisma.usersWhereInput | boolean
  delete?: Prisma.usersWhereInput | boolean
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutAuth_audit_logsInput, Prisma.usersUpdateWithoutAuth_audit_logsInput>, Prisma.usersUncheckedUpdateWithoutAuth_audit_logsInput>
}

export type usersCreateNestedOneWithoutOtp_codesInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutOtp_codesInput, Prisma.usersUncheckedCreateWithoutOtp_codesInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutOtp_codesInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneRequiredWithoutOtp_codesNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutOtp_codesInput, Prisma.usersUncheckedCreateWithoutOtp_codesInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutOtp_codesInput
  upsert?: Prisma.usersUpsertWithoutOtp_codesInput
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutOtp_codesInput, Prisma.usersUpdateWithoutOtp_codesInput>, Prisma.usersUncheckedUpdateWithoutOtp_codesInput>
}

export type usersCreateNestedManyWithoutPersonsInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutPersonsInput, Prisma.usersUncheckedCreateWithoutPersonsInput> | Prisma.usersCreateWithoutPersonsInput[] | Prisma.usersUncheckedCreateWithoutPersonsInput[]
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutPersonsInput | Prisma.usersCreateOrConnectWithoutPersonsInput[]
  createMany?: Prisma.usersCreateManyPersonsInputEnvelope
  connect?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
}

export type usersUncheckedCreateNestedManyWithoutPersonsInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutPersonsInput, Prisma.usersUncheckedCreateWithoutPersonsInput> | Prisma.usersCreateWithoutPersonsInput[] | Prisma.usersUncheckedCreateWithoutPersonsInput[]
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutPersonsInput | Prisma.usersCreateOrConnectWithoutPersonsInput[]
  createMany?: Prisma.usersCreateManyPersonsInputEnvelope
  connect?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
}

export type usersUpdateManyWithoutPersonsNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutPersonsInput, Prisma.usersUncheckedCreateWithoutPersonsInput> | Prisma.usersCreateWithoutPersonsInput[] | Prisma.usersUncheckedCreateWithoutPersonsInput[]
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutPersonsInput | Prisma.usersCreateOrConnectWithoutPersonsInput[]
  upsert?: Prisma.usersUpsertWithWhereUniqueWithoutPersonsInput | Prisma.usersUpsertWithWhereUniqueWithoutPersonsInput[]
  createMany?: Prisma.usersCreateManyPersonsInputEnvelope
  set?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  disconnect?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  delete?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  connect?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  update?: Prisma.usersUpdateWithWhereUniqueWithoutPersonsInput | Prisma.usersUpdateWithWhereUniqueWithoutPersonsInput[]
  updateMany?: Prisma.usersUpdateManyWithWhereWithoutPersonsInput | Prisma.usersUpdateManyWithWhereWithoutPersonsInput[]
  deleteMany?: Prisma.usersScalarWhereInput | Prisma.usersScalarWhereInput[]
}

export type usersUncheckedUpdateManyWithoutPersonsNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutPersonsInput, Prisma.usersUncheckedCreateWithoutPersonsInput> | Prisma.usersCreateWithoutPersonsInput[] | Prisma.usersUncheckedCreateWithoutPersonsInput[]
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutPersonsInput | Prisma.usersCreateOrConnectWithoutPersonsInput[]
  upsert?: Prisma.usersUpsertWithWhereUniqueWithoutPersonsInput | Prisma.usersUpsertWithWhereUniqueWithoutPersonsInput[]
  createMany?: Prisma.usersCreateManyPersonsInputEnvelope
  set?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  disconnect?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  delete?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  connect?: Prisma.usersWhereUniqueInput | Prisma.usersWhereUniqueInput[]
  update?: Prisma.usersUpdateWithWhereUniqueWithoutPersonsInput | Prisma.usersUpdateWithWhereUniqueWithoutPersonsInput[]
  updateMany?: Prisma.usersUpdateManyWithWhereWithoutPersonsInput | Prisma.usersUpdateManyWithWhereWithoutPersonsInput[]
  deleteMany?: Prisma.usersScalarWhereInput | Prisma.usersScalarWhereInput[]
}

export type usersCreateNestedOneWithoutRefresh_tokensInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutRefresh_tokensInput, Prisma.usersUncheckedCreateWithoutRefresh_tokensInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutRefresh_tokensInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneRequiredWithoutRefresh_tokensNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutRefresh_tokensInput, Prisma.usersUncheckedCreateWithoutRefresh_tokensInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutRefresh_tokensInput
  upsert?: Prisma.usersUpsertWithoutRefresh_tokensInput
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutRefresh_tokensInput, Prisma.usersUpdateWithoutRefresh_tokensInput>, Prisma.usersUncheckedUpdateWithoutRefresh_tokensInput>
}

export type usersCreateWithoutActive_sessionsInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  auth_audit_logs?: Prisma.auth_audit_logsCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensCreateNestedManyWithoutUsersInput
  persons: Prisma.personsCreateNestedOneWithoutUsersInput
}

export type usersUncheckedCreateWithoutActive_sessionsInput = {
  id?: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesUncheckedCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutActive_sessionsInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutActive_sessionsInput, Prisma.usersUncheckedCreateWithoutActive_sessionsInput>
}

export type usersUpsertWithoutActive_sessionsInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutActive_sessionsInput, Prisma.usersUncheckedUpdateWithoutActive_sessionsInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutActive_sessionsInput, Prisma.usersUncheckedCreateWithoutActive_sessionsInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutActive_sessionsInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutActive_sessionsInput, Prisma.usersUncheckedUpdateWithoutActive_sessionsInput>
}

export type usersUpdateWithoutActive_sessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_audit_logs?: Prisma.auth_audit_logsUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUpdateManyWithoutUsersNestedInput
  persons?: Prisma.personsUpdateOneRequiredWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutActive_sessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  person_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUncheckedUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateWithoutAuth_audit_logsInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensCreateNestedManyWithoutUsersInput
  persons: Prisma.personsCreateNestedOneWithoutUsersInput
}

export type usersUncheckedCreateWithoutAuth_audit_logsInput = {
  id?: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesUncheckedCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutAuth_audit_logsInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutAuth_audit_logsInput, Prisma.usersUncheckedCreateWithoutAuth_audit_logsInput>
}

export type usersUpsertWithoutAuth_audit_logsInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutAuth_audit_logsInput, Prisma.usersUncheckedUpdateWithoutAuth_audit_logsInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutAuth_audit_logsInput, Prisma.usersUncheckedCreateWithoutAuth_audit_logsInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutAuth_audit_logsInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutAuth_audit_logsInput, Prisma.usersUncheckedUpdateWithoutAuth_audit_logsInput>
}

export type usersUpdateWithoutAuth_audit_logsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUpdateManyWithoutUsersNestedInput
  persons?: Prisma.personsUpdateOneRequiredWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutAuth_audit_logsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  person_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUncheckedUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateWithoutOtp_codesInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensCreateNestedManyWithoutUsersInput
  persons: Prisma.personsCreateNestedOneWithoutUsersInput
}

export type usersUncheckedCreateWithoutOtp_codesInput = {
  id?: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutOtp_codesInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutOtp_codesInput, Prisma.usersUncheckedCreateWithoutOtp_codesInput>
}

export type usersUpsertWithoutOtp_codesInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutOtp_codesInput, Prisma.usersUncheckedUpdateWithoutOtp_codesInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutOtp_codesInput, Prisma.usersUncheckedCreateWithoutOtp_codesInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutOtp_codesInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutOtp_codesInput, Prisma.usersUncheckedUpdateWithoutOtp_codesInput>
}

export type usersUpdateWithoutOtp_codesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUpdateManyWithoutUsersNestedInput
  persons?: Prisma.personsUpdateOneRequiredWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutOtp_codesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  person_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateWithoutPersonsInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensCreateNestedManyWithoutUsersInput
}

export type usersUncheckedCreateWithoutPersonsInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesUncheckedCreateNestedManyWithoutUsersInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutPersonsInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutPersonsInput, Prisma.usersUncheckedCreateWithoutPersonsInput>
}

export type usersCreateManyPersonsInputEnvelope = {
  data: Prisma.usersCreateManyPersonsInput | Prisma.usersCreateManyPersonsInput[]
  skipDuplicates?: boolean
}

export type usersUpsertWithWhereUniqueWithoutPersonsInput = {
  where: Prisma.usersWhereUniqueInput
  update: Prisma.XOR<Prisma.usersUpdateWithoutPersonsInput, Prisma.usersUncheckedUpdateWithoutPersonsInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutPersonsInput, Prisma.usersUncheckedCreateWithoutPersonsInput>
}

export type usersUpdateWithWhereUniqueWithoutPersonsInput = {
  where: Prisma.usersWhereUniqueInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutPersonsInput, Prisma.usersUncheckedUpdateWithoutPersonsInput>
}

export type usersUpdateManyWithWhereWithoutPersonsInput = {
  where: Prisma.usersScalarWhereInput
  data: Prisma.XOR<Prisma.usersUpdateManyMutationInput, Prisma.usersUncheckedUpdateManyWithoutPersonsInput>
}

export type usersScalarWhereInput = {
  AND?: Prisma.usersScalarWhereInput | Prisma.usersScalarWhereInput[]
  OR?: Prisma.usersScalarWhereInput[]
  NOT?: Prisma.usersScalarWhereInput | Prisma.usersScalarWhereInput[]
  id?: Prisma.UuidFilter<"users"> | string
  person_id?: Prisma.UuidFilter<"users"> | string
  email?: Prisma.StringFilter<"users"> | string
  phone?: Prisma.StringFilter<"users"> | string
  password_hash?: Prisma.StringFilter<"users"> | string
  two_factor_method?: Prisma.BoolNullableFilter<"users"> | boolean | null
  is_active?: Prisma.BoolNullableFilter<"users"> | boolean | null
  failed_attempts?: Prisma.IntNullableFilter<"users"> | number | null
  blocked_until?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  last_login_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
}

export type usersCreateWithoutRefresh_tokensInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesCreateNestedManyWithoutUsersInput
  persons: Prisma.personsCreateNestedOneWithoutUsersInput
}

export type usersUncheckedCreateWithoutRefresh_tokensInput = {
  id?: string
  person_id: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedCreateNestedManyWithoutUsersInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedCreateNestedManyWithoutUsersInput
  otp_codes?: Prisma.otp_codesUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutRefresh_tokensInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutRefresh_tokensInput, Prisma.usersUncheckedCreateWithoutRefresh_tokensInput>
}

export type usersUpsertWithoutRefresh_tokensInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutRefresh_tokensInput, Prisma.usersUncheckedUpdateWithoutRefresh_tokensInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutRefresh_tokensInput, Prisma.usersUncheckedCreateWithoutRefresh_tokensInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutRefresh_tokensInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutRefresh_tokensInput, Prisma.usersUncheckedUpdateWithoutRefresh_tokensInput>
}

export type usersUpdateWithoutRefresh_tokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUpdateManyWithoutUsersNestedInput
  persons?: Prisma.personsUpdateOneRequiredWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutRefresh_tokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  person_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateManyPersonsInput = {
  id?: string
  email: string
  phone: string
  password_hash: string
  two_factor_method?: boolean | null
  is_active?: boolean | null
  failed_attempts?: number | null
  blocked_until?: Date | string | null
  last_login_at?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  deleted_at?: Date | string | null
}

export type usersUpdateWithoutPersonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUpdateManyWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutPersonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  active_sessions?: Prisma.active_sessionsUncheckedUpdateManyWithoutUsersNestedInput
  auth_audit_logs?: Prisma.auth_audit_logsUncheckedUpdateManyWithoutUsersNestedInput
  otp_codes?: Prisma.otp_codesUncheckedUpdateManyWithoutUsersNestedInput
  refresh_tokens?: Prisma.refresh_tokensUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersUncheckedUpdateManyWithoutPersonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  two_factor_method?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  failed_attempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  blocked_until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type UsersCountOutputType
 */

export type UsersCountOutputType = {
  active_sessions: number
  auth_audit_logs: number
  otp_codes: number
  refresh_tokens: number
}

export type UsersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  active_sessions?: boolean | UsersCountOutputTypeCountActive_sessionsArgs
  auth_audit_logs?: boolean | UsersCountOutputTypeCountAuth_audit_logsArgs
  otp_codes?: boolean | UsersCountOutputTypeCountOtp_codesArgs
  refresh_tokens?: boolean | UsersCountOutputTypeCountRefresh_tokensArgs
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersCountOutputType
   */
  select?: Prisma.UsersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountActive_sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.active_sessionsWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountAuth_audit_logsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.auth_audit_logsWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountOtp_codesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.otp_codesWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountRefresh_tokensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.refresh_tokensWhereInput
}


export type usersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  person_id?: boolean
  email?: boolean
  phone?: boolean
  password_hash?: boolean
  two_factor_method?: boolean
  is_active?: boolean
  failed_attempts?: boolean
  blocked_until?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  active_sessions?: boolean | Prisma.users$active_sessionsArgs<ExtArgs>
  auth_audit_logs?: boolean | Prisma.users$auth_audit_logsArgs<ExtArgs>
  otp_codes?: boolean | Prisma.users$otp_codesArgs<ExtArgs>
  refresh_tokens?: boolean | Prisma.users$refresh_tokensArgs<ExtArgs>
  persons?: boolean | Prisma.personsDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type usersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  person_id?: boolean
  email?: boolean
  phone?: boolean
  password_hash?: boolean
  two_factor_method?: boolean
  is_active?: boolean
  failed_attempts?: boolean
  blocked_until?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  persons?: boolean | Prisma.personsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type usersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  person_id?: boolean
  email?: boolean
  phone?: boolean
  password_hash?: boolean
  two_factor_method?: boolean
  is_active?: boolean
  failed_attempts?: boolean
  blocked_until?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  persons?: boolean | Prisma.personsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type usersSelectScalar = {
  id?: boolean
  person_id?: boolean
  email?: boolean
  phone?: boolean
  password_hash?: boolean
  two_factor_method?: boolean
  is_active?: boolean
  failed_attempts?: boolean
  blocked_until?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}

export type usersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "person_id" | "email" | "phone" | "password_hash" | "two_factor_method" | "is_active" | "failed_attempts" | "blocked_until" | "last_login_at" | "created_at" | "updated_at" | "deleted_at", ExtArgs["result"]["users"]>
export type usersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  active_sessions?: boolean | Prisma.users$active_sessionsArgs<ExtArgs>
  auth_audit_logs?: boolean | Prisma.users$auth_audit_logsArgs<ExtArgs>
  otp_codes?: boolean | Prisma.users$otp_codesArgs<ExtArgs>
  refresh_tokens?: boolean | Prisma.users$refresh_tokensArgs<ExtArgs>
  persons?: boolean | Prisma.personsDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}
export type usersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  persons?: boolean | Prisma.personsDefaultArgs<ExtArgs>
}
export type usersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  persons?: boolean | Prisma.personsDefaultArgs<ExtArgs>
}

export type $usersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "users"
  objects: {
    active_sessions: Prisma.$active_sessionsPayload<ExtArgs>[]
    auth_audit_logs: Prisma.$auth_audit_logsPayload<ExtArgs>[]
    otp_codes: Prisma.$otp_codesPayload<ExtArgs>[]
    refresh_tokens: Prisma.$refresh_tokensPayload<ExtArgs>[]
    persons: Prisma.$personsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    person_id: string
    email: string
    phone: string
    password_hash: string
    two_factor_method: boolean | null
    is_active: boolean | null
    failed_attempts: number | null
    blocked_until: Date | null
    last_login_at: Date | null
    created_at: Date | null
    updated_at: Date | null
    deleted_at: Date | null
  }, ExtArgs["result"]["users"]>
  composites: {}
}

export type usersGetPayload<S extends boolean | null | undefined | usersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$usersPayload, S>

export type usersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<usersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsersCountAggregateInputType | true
  }

export interface usersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['users'], meta: { name: 'users' } }
  /**
   * Find zero or one Users that matches the filter.
   * @param {usersFindUniqueArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends usersFindUniqueArgs>(args: Prisma.SelectSubset<T, usersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Users that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {usersFindUniqueOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends usersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, usersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersFindFirstArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends usersFindFirstArgs>(args?: Prisma.SelectSubset<T, usersFindFirstArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersFindFirstOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends usersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, usersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.users.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.users.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const usersWithIdOnly = await prisma.users.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends usersFindManyArgs>(args?: Prisma.SelectSubset<T, usersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Users.
   * @param {usersCreateArgs} args - Arguments to create a Users.
   * @example
   * // Create one Users
   * const Users = await prisma.users.create({
   *   data: {
   *     // ... data to create a Users
   *   }
   * })
   * 
   */
  create<T extends usersCreateArgs>(args: Prisma.SelectSubset<T, usersCreateArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {usersCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends usersCreateManyArgs>(args?: Prisma.SelectSubset<T, usersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {usersCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends usersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, usersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Users.
   * @param {usersDeleteArgs} args - Arguments to delete one Users.
   * @example
   * // Delete one Users
   * const Users = await prisma.users.delete({
   *   where: {
   *     // ... filter to delete one Users
   *   }
   * })
   * 
   */
  delete<T extends usersDeleteArgs>(args: Prisma.SelectSubset<T, usersDeleteArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Users.
   * @param {usersUpdateArgs} args - Arguments to update one Users.
   * @example
   * // Update one Users
   * const users = await prisma.users.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends usersUpdateArgs>(args: Prisma.SelectSubset<T, usersUpdateArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {usersDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.users.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends usersDeleteManyArgs>(args?: Prisma.SelectSubset<T, usersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends usersUpdateManyArgs>(args: Prisma.SelectSubset<T, usersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {usersUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends usersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, usersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Users.
   * @param {usersUpsertArgs} args - Arguments to update or create a Users.
   * @example
   * // Update or create a Users
   * const users = await prisma.users.upsert({
   *   create: {
   *     // ... data to create a Users
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Users we want to update
   *   }
   * })
   */
  upsert<T extends usersUpsertArgs>(args: Prisma.SelectSubset<T, usersUpsertArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.users.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends usersCountArgs>(
    args?: Prisma.Subset<T, usersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsersAggregateArgs>(args: Prisma.Subset<T, UsersAggregateArgs>): Prisma.PrismaPromise<GetUsersAggregateType<T>>

  /**
   * Group by Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends usersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: usersGroupByArgs['orderBy'] }
      : { orderBy?: usersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, usersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the users model
 */
readonly fields: usersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for users.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__usersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  active_sessions<T extends Prisma.users$active_sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$active_sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$active_sessionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  auth_audit_logs<T extends Prisma.users$auth_audit_logsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$auth_audit_logsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_audit_logsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  otp_codes<T extends Prisma.users$otp_codesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$otp_codesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$otp_codesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  refresh_tokens<T extends Prisma.users$refresh_tokensArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$refresh_tokensArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  persons<T extends Prisma.personsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.personsDefaultArgs<ExtArgs>>): Prisma.Prisma__personsClient<runtime.Types.Result.GetResult<Prisma.$personsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the users model
 */
export interface usersFieldRefs {
  readonly id: Prisma.FieldRef<"users", 'String'>
  readonly person_id: Prisma.FieldRef<"users", 'String'>
  readonly email: Prisma.FieldRef<"users", 'String'>
  readonly phone: Prisma.FieldRef<"users", 'String'>
  readonly password_hash: Prisma.FieldRef<"users", 'String'>
  readonly two_factor_method: Prisma.FieldRef<"users", 'Boolean'>
  readonly is_active: Prisma.FieldRef<"users", 'Boolean'>
  readonly failed_attempts: Prisma.FieldRef<"users", 'Int'>
  readonly blocked_until: Prisma.FieldRef<"users", 'DateTime'>
  readonly last_login_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"users", 'DateTime'>
}
    

// Custom InputTypes
/**
 * users findUnique
 */
export type usersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users findUniqueOrThrow
 */
export type usersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users findFirst
 */
export type usersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for users.
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * users findFirstOrThrow
 */
export type usersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for users.
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * users findMany
 */
export type usersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing users.
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * users create
 */
export type usersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * The data needed to create a users.
   */
  data: Prisma.XOR<Prisma.usersCreateInput, Prisma.usersUncheckedCreateInput>
}

/**
 * users createMany
 */
export type usersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many users.
   */
  data: Prisma.usersCreateManyInput | Prisma.usersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * users createManyAndReturn
 */
export type usersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * The data used to create many users.
   */
  data: Prisma.usersCreateManyInput | Prisma.usersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * users update
 */
export type usersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * The data needed to update a users.
   */
  data: Prisma.XOR<Prisma.usersUpdateInput, Prisma.usersUncheckedUpdateInput>
  /**
   * Choose, which users to update.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users updateMany
 */
export type usersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update users.
   */
  data: Prisma.XOR<Prisma.usersUpdateManyMutationInput, Prisma.usersUncheckedUpdateManyInput>
  /**
   * Filter which users to update
   */
  where?: Prisma.usersWhereInput
  /**
   * Limit how many users to update.
   */
  limit?: number
}

/**
 * users updateManyAndReturn
 */
export type usersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * The data used to update users.
   */
  data: Prisma.XOR<Prisma.usersUpdateManyMutationInput, Prisma.usersUncheckedUpdateManyInput>
  /**
   * Filter which users to update
   */
  where?: Prisma.usersWhereInput
  /**
   * Limit how many users to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * users upsert
 */
export type usersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * The filter to search for the users to update in case it exists.
   */
  where: Prisma.usersWhereUniqueInput
  /**
   * In case the users found by the `where` argument doesn't exist, create a new users with this data.
   */
  create: Prisma.XOR<Prisma.usersCreateInput, Prisma.usersUncheckedCreateInput>
  /**
   * In case the users was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.usersUpdateInput, Prisma.usersUncheckedUpdateInput>
}

/**
 * users delete
 */
export type usersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter which users to delete.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users deleteMany
 */
export type usersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which users to delete
   */
  where?: Prisma.usersWhereInput
  /**
   * Limit how many users to delete.
   */
  limit?: number
}

/**
 * users.active_sessions
 */
export type users$active_sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the active_sessions
   */
  select?: Prisma.active_sessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the active_sessions
   */
  omit?: Prisma.active_sessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.active_sessionsInclude<ExtArgs> | null
  where?: Prisma.active_sessionsWhereInput
  orderBy?: Prisma.active_sessionsOrderByWithRelationInput | Prisma.active_sessionsOrderByWithRelationInput[]
  cursor?: Prisma.active_sessionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Active_sessionsScalarFieldEnum | Prisma.Active_sessionsScalarFieldEnum[]
}

/**
 * users.auth_audit_logs
 */
export type users$auth_audit_logsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_audit_logs
   */
  select?: Prisma.auth_audit_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_audit_logs
   */
  omit?: Prisma.auth_audit_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_audit_logsInclude<ExtArgs> | null
  where?: Prisma.auth_audit_logsWhereInput
  orderBy?: Prisma.auth_audit_logsOrderByWithRelationInput | Prisma.auth_audit_logsOrderByWithRelationInput[]
  cursor?: Prisma.auth_audit_logsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Auth_audit_logsScalarFieldEnum | Prisma.Auth_audit_logsScalarFieldEnum[]
}

/**
 * users.otp_codes
 */
export type users$otp_codesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the otp_codes
   */
  select?: Prisma.otp_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the otp_codes
   */
  omit?: Prisma.otp_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.otp_codesInclude<ExtArgs> | null
  where?: Prisma.otp_codesWhereInput
  orderBy?: Prisma.otp_codesOrderByWithRelationInput | Prisma.otp_codesOrderByWithRelationInput[]
  cursor?: Prisma.otp_codesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Otp_codesScalarFieldEnum | Prisma.Otp_codesScalarFieldEnum[]
}

/**
 * users.refresh_tokens
 */
export type users$refresh_tokensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  where?: Prisma.refresh_tokensWhereInput
  orderBy?: Prisma.refresh_tokensOrderByWithRelationInput | Prisma.refresh_tokensOrderByWithRelationInput[]
  cursor?: Prisma.refresh_tokensWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Refresh_tokensScalarFieldEnum | Prisma.Refresh_tokensScalarFieldEnum[]
}

/**
 * users without action
 */
export type usersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
}
